\set ON_ERROR_STOP on

create role anon nologin;
create role authenticated nologin;
create schema auth;

create function auth.uid()
returns uuid
language sql
stable
as $$ select nullif(current_setting('request.jwt.claim.sub', true), '')::uuid $$;

create table public.community_profiles (
    id uuid primary key,
    auth_user_id uuid unique,
    account_status text not null default 'active'
);
create table public.chat_threads (id bigint primary key);
create table public.chat_participants (
    thread_id bigint not null references public.chat_threads(id) on delete cascade,
    profile_id uuid not null references public.community_profiles(id) on delete cascade,
    left_at timestamptz,
    primary key (thread_id, profile_id)
);
create table public.chat_messages (
    id bigint primary key,
    thread_id bigint not null references public.chat_threads(id) on delete cascade,
    sender_profile_id uuid not null references public.community_profiles(id),
    body text not null,
    edited_at timestamptz,
    deleted_at timestamptz,
    deleted_by_profile_id uuid references public.community_profiles(id),
    updated_at timestamptz not null default now()
);
create table public.chat_events (
    id bigint generated by default as identity primary key,
    thread_id bigint references public.chat_threads(id) on delete cascade,
    actor_profile_id uuid references public.community_profiles(id) on delete set null,
    event_type text not null,
    payload jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);

create function public.quata_chat_actor_profile_id(p_actor_profile_id uuid default null)
returns uuid
language plpgsql stable security definer set search_path = public, auth
as $$
declare v_actor uuid;
begin
    select id into v_actor from public.community_profiles
     where auth_user_id = auth.uid() and account_status = 'active';
    if v_actor is null or (p_actor_profile_id is not null and p_actor_profile_id <> v_actor) then
        raise exception 'authenticated chat actor is required' using errcode = '42501';
    end if;
    return v_actor;
end;
$$;

create function public.quata_chat_is_thread_participant(p_thread_id bigint, p_profile_id uuid)
returns boolean language sql stable
as $$ select exists(select 1 from public.chat_participants where thread_id=p_thread_id and profile_id=p_profile_id and left_at is null) $$;

create function public.quata_chat_get_thread(p_actor_profile_id uuid, p_thread_id bigint)
returns jsonb language sql stable
as $$
    select jsonb_build_object(
        'thread_id', p_thread_id,
        'actor', p_actor_profile_id,
        'messages', coalesce(jsonb_agg(jsonb_build_object('id',m.id,'body',m.body,'deleted',m.deleted_at is not null) order by m.id), '[]'::jsonb)
    ) from public.chat_messages m where m.thread_id=p_thread_id
$$;

-- Legacy signatures are fingerprints: the v2 migration must not replace them.
create function public.quata_chat_edit_message(uuid,bigint,bigint,text)
returns jsonb language sql as $$ select '{"legacy":"edit"}'::jsonb $$;
create function public.quata_chat_delete_messages(uuid,bigint,bigint[])
returns jsonb language sql as $$ select '{"legacy":"delete"}'::jsonb $$;
create table public.legacy_function_fingerprint(name text primary key, value text not null);
insert into public.legacy_function_fingerprint values
 ('edit', md5(pg_get_functiondef('public.quata_chat_edit_message(uuid,bigint,bigint,text)'::regprocedure))),
 ('delete', md5(pg_get_functiondef('public.quata_chat_delete_messages(uuid,bigint,bigint[])'::regprocedure)));

insert into public.community_profiles(id,auth_user_id) values
 ('00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000001'),
 ('00000000-0000-0000-0000-000000000002','10000000-0000-0000-0000-000000000002');
insert into public.chat_threads values (77);
insert into public.chat_participants(thread_id,profile_id) values
 (77,'00000000-0000-0000-0000-000000000001'),
 (77,'00000000-0000-0000-0000-000000000002');
insert into public.chat_messages(id,thread_id,sender_profile_id,body) values
 (101,77,'00000000-0000-0000-0000-000000000001','before'),
 (102,77,'00000000-0000-0000-0000-000000000001','delete me'),
 (103,77,'00000000-0000-0000-0000-000000000002','other');

do $$
declare
    v_denied boolean := false;
begin
    perform set_config('request.jwt.claim.sub','10000000-0000-0000-0000-000000000001',true);

    perform public.quata_chat_edit_message_v2(
        '00000000-0000-0000-0000-000000000001',77,101,'after','chat-mutation-edit-000001'
    );
    perform public.quata_chat_edit_message_v2(
        '00000000-0000-0000-0000-000000000001',77,101,'after','chat-mutation-edit-000001'
    );
    if (select body <> 'after' from public.chat_messages where id=101) then
        raise exception 'edit was not applied';
    end if;
    if (select count(*) <> 1 from public.chat_events where event_type='message_edited' and payload->>'message_id'='101') then
        raise exception 'edit replay repeated its event';
    end if;

    begin
        perform public.quata_chat_edit_message_v2(
            '00000000-0000-0000-0000-000000000001',77,101,'different','chat-mutation-edit-000001'
        );
    exception when sqlstate '22023' then v_denied := true;
    end;
    if not v_denied then raise exception 'edit key reuse was accepted'; end if;

    perform public.quata_chat_delete_messages_v2(
        '00000000-0000-0000-0000-000000000001',77,array[102]::bigint[],'chat-mutation-delete-0001'
    );
    perform public.quata_chat_delete_messages_v2(
        '00000000-0000-0000-0000-000000000001',77,array[102]::bigint[],'chat-mutation-delete-0001'
    );
    if (select deleted_at is null from public.chat_messages where id=102) then
        raise exception 'delete was not applied';
    end if;
    if (select count(*) <> 1 from public.chat_events where event_type='messages_deleted' and payload->'message_ids' @> '[102]'::jsonb) then
        raise exception 'delete replay repeated its event';
    end if;
    if (select count(*) <> 2 from public.chat_message_mutation_receipts where completed_at is not null) then
        raise exception 'completed receipt count mismatch';
    end if;

    v_denied := false;
    begin
        perform public.quata_chat_delete_messages_v2(
            '00000000-0000-0000-0000-000000000001',77,array[103]::bigint[],'chat-mutation-delete-0002'
        );
    exception when sqlstate '42501' then v_denied := true;
    end;
    if not v_denied then raise exception 'foreign message deletion was accepted'; end if;

    if md5(pg_get_functiondef('public.quata_chat_edit_message(uuid,bigint,bigint,text)'::regprocedure)) <>
       (select value from public.legacy_function_fingerprint where name='edit') then
        raise exception 'legacy edit function changed';
    end if;
    if md5(pg_get_functiondef('public.quata_chat_delete_messages(uuid,bigint,bigint[])'::regprocedure)) <>
       (select value from public.legacy_function_fingerprint where name='delete') then
        raise exception 'legacy delete function changed';
    end if;
end;
$$;

do $$
declare v_denied boolean := false;
begin
    perform set_config('request.jwt.claim.sub','10000000-0000-0000-0000-000000000002',true);
    begin
        perform public.quata_chat_edit_message_v2(
            '00000000-0000-0000-0000-000000000001',77,101,'stolen','chat-mutation-edit-000002'
        );
    exception when sqlstate '42501' then v_denied := true;
    end;
    if not v_denied then raise exception 'actor mismatch was accepted'; end if;
end;
$$;
