package com.quata.feature.postcomposer.videoeditor

const val PostVideoEditorRootTestTag = "post-video-editor.root"
const val PostVideoEditorPreviewTestTag = "post-video-editor.preview"
const val PostVideoEditorMuteTestTag = "post-video-editor.mute"
const val PostVideoEditorCropTestTag = "post-video-editor.crop"
const val PostVideoEditorCaptionsTestTag = "post-video-editor.captions"
const val PostVideoEditorExportTestTag = "post-video-editor.export"
const val PostVideoEditorExportProgressTestTag = "post-video-editor.export-progress"
const val PostVideoEditorTimelineTestTag = "post-video-editor.timeline"
const val PostVideoEditorTrimStartHandleTestTag = "post-video-editor.trim-start"
const val PostVideoEditorTrimEndHandleTestTag = "post-video-editor.trim-end"
const val PostVideoEditorPlayPauseTestTag = "post-video-editor.play-pause"
const val PostVideoEditorErrorTestTag = "post-video-editor.error"
const val PostVideoEditorResetTestTag = "post-video-editor.reset"
const val PostVideoEditorCancelExportTestTag = "post-video-editor.cancel-export"
