package com.quata.feature.chat.presentation.chat

sealed class ChatUiEvent {
    data class MessageChanged(val value: String) : ChatUiEvent()
    data class ParticipantSearchChanged(val value: String) : ChatUiEvent()
    data class ParticipantSelectionToggled(val userId: String) : ChatUiEvent()
    data class MessageSelected(val messageId: String?) : ChatUiEvent()
    data class ForwardConversationToggled(val conversationId: String) : ChatUiEvent()
    data class ConversationMutedChanged(val muted: Boolean) : ChatUiEvent()
    data class MemberInvitesChanged(val enabled: Boolean) : ChatUiEvent()
    data object OpenAddParticipants : ChatUiEvent()
    data object CloseAddParticipants : ChatUiEvent()
    data object AddSelectedParticipants : ChatUiEvent()
    data object StartReply : ChatUiEvent()
    data object ClearReply : ChatUiEvent()
    data object StartEdit : ChatUiEvent()
    data object CancelEdit : ChatUiEvent()
    data object ToggleFavoriteSelected : ChatUiEvent()
    data object DeleteSelectedMessage : ChatUiEvent()
    data object OpenForwardDialog : ChatUiEvent()
    data object CloseForwardDialog : ChatUiEvent()
    data object SendForward : ChatUiEvent()
    data class PromoteModerator(val userId: String) : ChatUiEvent()
    data class RemoveParticipant(val userId: String) : ChatUiEvent()
    data class BlockParticipant(val userId: String) : ChatUiEvent()
    data object LeaveConversation : ChatUiEvent()
    data object HideConversation : ChatUiEvent()
    data object DeleteConversation : ChatUiEvent()
    data object Send : ChatUiEvent()
}
