package com.quata.feature.postcomposer.presentation

import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.heightIn
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.DisposableEffect
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import androidx.compose.ui.viewinterop.UIKitView
import com.quata.core.platform.PlatformFile
import com.quata.core.platform.PlatformResult
import kotlinx.cinterop.ExperimentalForeignApi
import platform.Foundation.NSURL
import platform.Foundation.NSFileManager
import platform.Foundation.NSTemporaryDirectory
import platform.ImageIO.CGImageSourceCreateThumbnailAtIndex
import platform.ImageIO.CGImageSourceCreateWithURL
import platform.ImageIO.kCGImageSourceCreateThumbnailFromImageAlways
import platform.ImageIO.kCGImageSourceCreateThumbnailWithTransform
import platform.ImageIO.kCGImageSourceThumbnailMaxPixelSize
import platform.UIKit.UIImage
import platform.UIKit.UIImageView
import platform.UIKit.UIViewContentModeScaleAspectFit

/** A truthful local-only media preview. It never asks UIKit to resolve a remote URL. */
@Composable
internal fun IosComposerLocalImagePreview(file: PlatformFile, modifier: Modifier = Modifier) {
    var preview by remember(file.reference) { mutableStateOf<IosComposerImagePreview>(IosComposerImagePreview.Loading) }
    LaunchedEffect(file.reference) { preview = IosComposerPreviewImageCache.acquire(file) }
    DisposableEffect(file.reference) {
        onDispose { IosComposerPreviewImageCache.release(file) }
    }
    when (val value = preview) {
        IosComposerImagePreview.Loading -> Text("Loading local image preview...")
        is IosComposerImagePreview.Image -> {
            UIKitView(
                factory = {
                    UIImageView().apply {
                        contentMode = UIViewContentModeScaleAspectFit
                        clipsToBounds = true
                        image = value.value
                    }
                },
                update = { it.image = value.value },
                modifier = modifier.fillMaxWidth().heightIn(min = 160.dp, max = 320.dp),
            )
        }
        IosComposerImagePreview.Unavailable -> {
            // A selected file is not evidence that UIKit can decode it. Keep that distinction visible.
            Text("Local image preview unavailable")
        }
    }
}

internal sealed interface IosComposerImagePreview {
    data object Loading : IosComposerImagePreview
    data class Image(val value: UIImage) : IosComposerImagePreview
    data object Unavailable : IosComposerImagePreview
}

/**
 * Bounded decode cache for the temporary files provided by iOS adapters. Loading happens from a
 * [LaunchedEffect], never from the composable body; the cache holds one image per active path.
 */
private object IosComposerPreviewImageCache {
    private val images = mutableMapOf<String, IosComposerImagePreview>()

    fun acquire(file: PlatformFile): IosComposerImagePreview = images.getOrPut(file.reference) {
        file.localThumbnailOrNull()?.let(IosComposerImagePreview::Image) ?: IosComposerImagePreview.Unavailable
    }

    fun release(file: PlatformFile) {
        images.remove(file.reference)
    }
}

internal sealed interface IosComposerVideoPreview {
    data object Generating : IosComposerVideoPreview
    data class Thumbnail(val file: PlatformFile) : IosComposerVideoPreview
    data class Unavailable(val reason: String) : IosComposerVideoPreview
}

/** Codec/decoder errors are explicit; they are not represented as a fake video card. */
internal fun PlatformResult<PlatformFile>.toIosComposerVideoPreview(): IosComposerVideoPreview = when (this) {
    is PlatformResult.Success -> IosComposerVideoPreview.Thumbnail(value)
    is PlatformResult.Failure -> IosComposerVideoPreview.Unavailable(reason ?: "video_thumbnail_unavailable")
    PlatformResult.Cancelled -> IosComposerVideoPreview.Unavailable("video_thumbnail_cancelled")
    PlatformResult.Unsupported -> IosComposerVideoPreview.Unavailable("video_thumbnail_unsupported")
}

/** Releases only a thumbnail generated by [IosVideoThumbnailService], never an arbitrary file. */
@OptIn(ExperimentalForeignApi::class)
internal fun releaseIosComposerVideoThumbnail(file: PlatformFile): Boolean {
    val reference = file.reference.trim()
    val url = when {
        reference.startsWith("file://") -> NSURL(string = reference)
        reference.startsWith("/") -> NSURL.fileURLWithPath(reference)
        else -> null
    }?.takeIf { it.isFileURL() } ?: return false
    val path = url.path ?: return false
    if (!isOwnedIosComposerVideoThumbnailPath(path, NSTemporaryDirectory())) return false
    return NSFileManager.defaultManager.removeItemAtURL(url, error = null)
}

@OptIn(ExperimentalForeignApi::class)
private fun PlatformFile.localThumbnailOrNull(): UIImage? {
    val value = reference.trim()
    val url = when {
        value.startsWith("file://") -> NSURL(string = value)
        value.startsWith("/") -> NSURL.fileURLWithPath(value)
        else -> null
    }?.takeIf { it.isFileURL() } ?: return null
    val source = CGImageSourceCreateWithURL(url, null) ?: return null
    val options = mapOf<Any?, Any?>(
        kCGImageSourceCreateThumbnailFromImageAlways to true,
        kCGImageSourceCreateThumbnailWithTransform to true,
        kCGImageSourceThumbnailMaxPixelSize to 640,
    )
    val image = CGImageSourceCreateThumbnailAtIndex(source, 0u, options) ?: return null
    return UIImage.imageWithCGImage(image)
}
