package com.quata.feature.chat.presentation.chat

/**
 * Product copy for the shared Chat chrome.
 *
 * Values intentionally mirror Android's `strings.xml`; platform adapters must not replace the
 * shared header, selection bar, group menu or confirmations with parallel UI.
 *
 * IDs: SCR-CHAT, CHAT-MESSAGE-ACTIONS, CHAT-GROUP, CHAT-NOTIFICATIONS.
 */
data class ChatChromeStrings(
    val untitledConversation: String,
    val favoriteMessages: String,
    val favoriteMessagesEmpty: String,
    val retryMessages: String,
    val retry: String,
    val back: String,
    val edited: String,
    val deletedMessage: String,
    val forwarded: String,
    val closeSelection: String,
    val copyMessage: String,
    val replyMessage: String,
    val forwardMessage: String,
    val editMessage: String,
    val reportMessage: String,
    val favoriteMessage: String,
    val favoriteMarker: String,
    val deleteMessage: String,
    val deleteMessageConfirm: String,
    val reportMessageConfirm: String,
    val confirm: String,
    val cancel: String,
    val options: String,
    val reactivateNotifications: String,
    val muteConversation: String,
    val allowMemberInvites: String,
    val addParticipants: String,
    val leaveConversation: String,
    val deleteConversation: String,
    val leaveConversationConfirm: String,
    val deleteConversationConfirm: String,
    val moderator: String,
    val promoteModerator: String,
    val removeModerator: String,
    val promoteModeratorConfirm: String,
    val removeModeratorConfirm: String,
    val blockUser: String,
    val blockUserConfirm: String,
    val removeParticipant: String,
    val removeParticipantConfirm: String,
    val search: String,
    val searchingPeople: String,
    val noPeopleFound: String,
    val loadMore: String,
    val loading: String,
    val add: String,
    val typing: String,
    val close: String,
    val forwardTitle: String,
    val message: String,
    val editingMessage: String,
    val attachment: String,
    val attachmentReady: String,
    val removeAttachment: String,
    val chooseFile: String,
    val chooseGallery: String,
    val openCamera: String,
    val recordAudio: String,
    val stopRecording: String,
    val stopAndAttach: String,
    val emoji: String,
    val attach: String,
    val send: String,
    val photo: String,
    val voiceNote: String,
    val filePickerError: String,
    val filePickerUnsupported: String,
    val galleryError: String,
    val galleryUnsupported: String,
    val cameraError: String,
    val cameraUnsupported: String,
    val audioStartError: String,
    val audioSaveError: String,
    val audioUnsupported: String,
    val playVideo: String,
    val playAudio: String,
    val pauseAudio: String,
    val memberCount: (Int) -> String,
    val memberLabel: (String, Boolean) -> String,
    val manageMember: (String) -> String,
    val replyingTo: (String) -> String,
    val recording: (String) -> String,
)

fun chatChromeStringsForLanguage(languageTag: String?): ChatChromeStrings =
    when (languageTag?.substringBefore('-')?.substringBefore('_')?.lowercase()) {
        "es" -> ChatChromeStrings(
            untitledConversation = "Chats",
            favoriteMessages = "Mensajes favoritos",
            favoriteMessagesEmpty = "Todavia no hay mensajes favoritos.",
            retryMessages = "Reintentar mensajes",
            retry = "Reintentar",
            back = "Volver",
            edited = "Editado",
            deletedMessage = "Mensaje eliminado",
            forwarded = "Reenviado",
            closeSelection = "Cerrar selección",
            copyMessage = "Copiar texto",
            replyMessage = "Responder",
            forwardMessage = "Reenviar",
            editMessage = "Editar",
            reportMessage = "Denunciar mensaje",
            favoriteMessage = "Favorito",
            favoriteMarker = "favorito",
            deleteMessage = "Eliminar mensaje",
            deleteMessageConfirm = "Este mensaje será eliminado de forma permanente.",
            reportMessageConfirm = "¿Enviar este mensaje al equipo de moderación de Qüata para que lo revise?",
            confirm = "Confirmar",
            cancel = "Cancelar",
            options = "Abrir",
            reactivateNotifications = "Reactivar notificaciones",
            muteConversation = "Silenciar conversación",
            allowMemberInvites = "Permitir que los miembros inviten",
            addParticipants = "Añadir nuevos participantes",
            leaveConversation = "Abandonar conversación",
            deleteConversation = "Borrar conversación",
            leaveConversationConfirm = "Dejarás de ser miembro de esta conversación.",
            deleteConversationConfirm = "La conversación desaparecerá ahora. Podrás deshacerlo unos segundos desde la lista de conversaciones.",
            moderator = "Moderador",
            promoteModerator = "Ascender a moderador",
            removeModerator = "Quitar de moderador",
            promoteModeratorConfirm = "Este participante pasará a ser moderador de la conversación.",
            removeModeratorConfirm = "Este participante dejará de ser moderador de la conversación.",
            blockUser = "Bloquear usuario",
            blockUserConfirm = "Este usuario se bloqueará y saldrá de la conversación.",
            removeParticipant = "Expulsar participante",
            removeParticipantConfirm = "Este participante saldrá de la conversación.",
            search = "Buscar",
            searchingPeople = "Buscando personas…",
            noPeopleFound = "No se encontraron personas.",
            loadMore = "Cargar más",
            loading = "Cargando…",
            add = "Añadir",
            typing = "Escribiendo…",
            close = "Cerrar",
            forwardTitle = "Reenviar mensaje",
            message = "Mensaje",
            editingMessage = "Editando mensaje",
            attachment = "Adjunto",
            attachmentReady = "Adjunto preparado",
            removeAttachment = "Quitar adjunto",
            chooseFile = "Elegir archivo",
            chooseGallery = "Foto/vídeo de galería",
            openCamera = "Abrir cámara",
            recordAudio = "Grabar audio",
            stopRecording = "Detener grabación",
            stopAndAttach = "Detener y adjuntar",
            emoji = "Emoji",
            attach = "Adjuntar",
            send = "Enviar",
            photo = "Foto",
            voiceNote = "Nota de voz",
            filePickerError = "No se pudo abrir el selector de archivos.",
            filePickerUnsupported = "El selector de archivos no está disponible en esta plataforma.",
            galleryError = "No se pudo abrir la galería.",
            galleryUnsupported = "La galería no está disponible en esta plataforma.",
            cameraError = "No se pudo abrir la cámara.",
            cameraUnsupported = "La cámara no está disponible en este dispositivo.",
            audioStartError = "No se pudo iniciar la grabación.",
            audioSaveError = "No se pudo guardar la grabación.",
            audioUnsupported = "La grabación de audio no está disponible.",
            playVideo = "Reproducir vídeo",
            playAudio = "Reproducir audio",
            pauseAudio = "Pausar audio",
            memberCount = { count -> "$count miembros" },
            memberLabel = { name, isSelf -> if (isSelf) "$name (tú)" else name },
            manageMember = { name -> "Gestionar $name" },
            replyingTo = { name -> "Respondiendo a $name" },
            recording = { elapsed -> "Grabando $elapsed" },
        )
        "fr" -> ChatChromeStrings(
            untitledConversation = "Chats",
            favoriteMessages = "Messages favoris",
            favoriteMessagesEmpty = "Aucun message favori.",
            retryMessages = "Réessayer les messages",
            retry = "Réessayer",
            back = "Retour",
            edited = "Modifié",
            deletedMessage = "Message supprimé",
            forwarded = "Transféré",
            closeSelection = "Fermer la sélection",
            copyMessage = "Copier texte",
            replyMessage = "Répondre",
            forwardMessage = "Transférer",
            editMessage = "Modifier",
            reportMessage = "Signaler le message",
            favoriteMessage = "Favori",
            favoriteMarker = "favori",
            deleteMessage = "Supprimer message",
            deleteMessageConfirm = "Ce message sera supprimé définitivement.",
            reportMessageConfirm = "Envoyer ce message à l'équipe de modération de Qüata pour examen ?",
            confirm = "Confirmer",
            cancel = "Annuler",
            options = "Ouvrir",
            reactivateNotifications = "Réactiver les notifications",
            muteConversation = "Mettre la conversation en sourdine",
            allowMemberInvites = "Autoriser les membres à inviter",
            addParticipants = "Ajouter de nouveaux participants",
            leaveConversation = "Quitter la conversation",
            deleteConversation = "Supprimer la conversation",
            leaveConversationConfirm = "Tu ne seras plus membre de cette conversation.",
            deleteConversationConfirm = "La conversation disparaîtra maintenant. Tu pourras l'annuler quelques secondes depuis la liste.",
            moderator = "Modérateur",
            promoteModerator = "Nommer modérateur",
            removeModerator = "Retirer modérateur",
            promoteModeratorConfirm = "Ce participant deviendra modérateur de la conversation.",
            removeModeratorConfirm = "Ce participant ne sera plus modérateur de la conversation.",
            blockUser = "Bloquer utilisateur",
            blockUserConfirm = "Cet utilisateur sera bloqué et sortira de la conversation.",
            removeParticipant = "Expulser participant",
            removeParticipantConfirm = "Ce participant sortira de la conversation.",
            search = "Chercher",
            searchingPeople = "Recherche de personnes…",
            noPeopleFound = "Aucune personne trouvée.",
            loadMore = "Charger plus",
            loading = "Chargement…",
            add = "Ajouter",
            typing = "Écriture…",
            close = "Fermer",
            forwardTitle = "Transférer message",
            message = "Message",
            editingMessage = "Modification du message",
            attachment = "Pièce jointe",
            attachmentReady = "Pièce jointe prête",
            removeAttachment = "Retirer la pièce jointe",
            chooseFile = "Choisir fichier",
            chooseGallery = "Photo/vidéo galerie",
            openCamera = "Ouvrir caméra",
            recordAudio = "Enregistrer audio",
            stopRecording = "Arrêter l'enregistrement",
            stopAndAttach = "Arrêter et joindre",
            emoji = "Emoji",
            attach = "Joindre",
            send = "Envoyer",
            photo = "Photo",
            voiceNote = "Note vocale",
            filePickerError = "Impossible d'ouvrir le sélecteur de fichiers.",
            filePickerUnsupported = "Le sélecteur de fichiers n'est pas disponible sur cette plateforme.",
            galleryError = "Impossible d'ouvrir la galerie.",
            galleryUnsupported = "La galerie n'est pas disponible sur cette plateforme.",
            cameraError = "Impossible d'ouvrir la caméra.",
            cameraUnsupported = "La caméra n'est pas disponible sur cet appareil.",
            audioStartError = "Impossible de démarrer l'enregistrement.",
            audioSaveError = "Impossible d'enregistrer l'audio.",
            audioUnsupported = "L'enregistrement audio n'est pas disponible.",
            playVideo = "Lire la vidéo",
            playAudio = "Lire l'audio",
            pauseAudio = "Mettre l'audio en pause",
            memberCount = { count -> "$count membres" },
            memberLabel = { name, isSelf -> if (isSelf) "$name (toi)" else name },
            manageMember = { name -> "Gérer $name" },
            replyingTo = { name -> "Réponse à $name" },
            recording = { elapsed -> "Enregistrement $elapsed" },
        )
        else -> ChatChromeStrings(
            untitledConversation = "Chats",
            favoriteMessages = "Favorite messages",
            favoriteMessagesEmpty = "No favorite messages yet.",
            retryMessages = "Retry messages",
            retry = "Retry",
            back = "Back",
            edited = "Edited",
            deletedMessage = "Message deleted",
            forwarded = "Forwarded",
            closeSelection = "Close selection",
            copyMessage = "Copy text",
            replyMessage = "Reply",
            forwardMessage = "Forward",
            editMessage = "Edit",
            reportMessage = "Report message",
            favoriteMessage = "Favorite",
            favoriteMarker = "favorite",
            deleteMessage = "Delete message",
            deleteMessageConfirm = "This message will be permanently deleted.",
            reportMessageConfirm = "Send this message to the Qüata moderation team for review?",
            confirm = "Confirm",
            cancel = "Cancel",
            options = "Open",
            reactivateNotifications = "Reactivate notifications",
            muteConversation = "Mute conversation",
            allowMemberInvites = "Allow members to invite",
            addParticipants = "Add new participants",
            leaveConversation = "Leave conversation",
            deleteConversation = "Delete conversation",
            leaveConversationConfirm = "You will no longer be a member of this conversation.",
            deleteConversationConfirm = "The conversation will disappear now. You can undo this for a few seconds from the conversations list.",
            moderator = "Moderator",
            promoteModerator = "Promote to moderator",
            removeModerator = "Remove moderator",
            promoteModeratorConfirm = "This participant will become a conversation moderator.",
            removeModeratorConfirm = "This participant will stop being a conversation moderator.",
            blockUser = "Block user",
            blockUserConfirm = "This user will be blocked and removed from the conversation.",
            removeParticipant = "Remove participant",
            removeParticipantConfirm = "This participant will be removed from the conversation.",
            search = "Search",
            searchingPeople = "Searching for people…",
            noPeopleFound = "No people found.",
            loadMore = "Load more",
            loading = "Loading…",
            add = "Add",
            typing = "Typing…",
            close = "Close",
            forwardTitle = "Forward message",
            message = "Message",
            editingMessage = "Editing message",
            attachment = "Attachment",
            attachmentReady = "Attachment ready",
            removeAttachment = "Remove attachment",
            chooseFile = "Choose file",
            chooseGallery = "Photo/video from gallery",
            openCamera = "Open camera",
            recordAudio = "Record audio",
            stopRecording = "Stop recording",
            stopAndAttach = "Stop and attach",
            emoji = "Emoji",
            attach = "Attach",
            send = "Send",
            photo = "Photo",
            voiceNote = "Voice note",
            filePickerError = "The file picker could not be opened.",
            filePickerUnsupported = "The file picker is not available on this platform.",
            galleryError = "The gallery could not be opened.",
            galleryUnsupported = "The gallery is not available on this platform.",
            cameraError = "The camera could not be opened.",
            cameraUnsupported = "The camera is not available on this device.",
            audioStartError = "The recording could not be started.",
            audioSaveError = "The recording could not be saved.",
            audioUnsupported = "Audio recording is not available.",
            playVideo = "Play video",
            playAudio = "Play audio",
            pauseAudio = "Pause audio",
            memberCount = { count -> "$count members" },
            memberLabel = { name, isSelf -> if (isSelf) "$name (you)" else name },
            manageMember = { name -> "Manage $name" },
            replyingTo = { name -> "Replying to $name" },
            recording = { elapsed -> "Recording $elapsed" },
        )
    }
