package com.quata.feature.chat.data

import com.quata.core.platform.PlatformFile
import com.quata.core.platform.PlatformResult
import kotlinx.cinterop.ExperimentalForeignApi
import kotlinx.cinterop.addressOf
import kotlinx.cinterop.readBytes
import kotlinx.cinterop.reinterpret
import kotlinx.cinterop.usePinned
import kotlinx.coroutines.CancellableContinuation
import kotlinx.coroutines.suspendCancellableCoroutine
import platform.CoreFoundation.CFDataCreate
import platform.Foundation.NSData
import platform.Foundation.NSError
import platform.Foundation.NSFileManager
import platform.Foundation.NSHTTPURLResponse
import platform.Foundation.NSMutableURLRequest
import platform.Foundation.NSURL
import platform.Foundation.NSURLRequest
import platform.Foundation.NSURLSession
import platform.Foundation.NSURLSessionConfiguration
import platform.Foundation.NSURLSessionDataDelegateProtocol
import platform.Foundation.NSURLSessionDataTask
import platform.Foundation.NSURLSessionTask
import platform.Foundation.NSUUID
import platform.Foundation.NSTemporaryDirectory
import platform.Foundation.setHTTPMethod
import platform.Foundation.setValue
import platform.darwin.NSObject
import kotlin.coroutines.resume
import kotlin.coroutines.resumeWithException

/**
 * Downloads a public Chat attachment into the app's temporary sandbox.
 *
 * This is intentionally separate from [IosChatAttachmentUploader]: message attachment URLs are
 * untrusted remote data, while uploads use the authenticated storage endpoint. The public GET
 * below has no session or API-key headers, rejects every redirect, and accepts only the canonical
 * public object URL generated by this Supabase deployment.
 */
@OptIn(ExperimentalForeignApi::class)
class IosChatAttachmentDownloader(
    private val configuration: IosChatRuntimeConfiguration,
) {
    suspend fun download(
        publicUrl: String,
        displayName: String? = null,
    ): PlatformResult<PlatformFile> {
        val canonicalUrl = ChatAttachmentPublicUrlPolicy.canonicalUrlOrNull(
            supabaseUrl = configuration.supabaseUrl,
            publicUrl = publicUrl,
        ) ?: return PlatformResult.Failure("ios_chat_attachment_url_invalid")

        return runCatching {
            val response = canonicalUrl.downloadPublicChatAttachment()
            val mimeType = response.mimeType?.normalisedChatMimeType()
                ?.takeIf(::isAllowedChatAttachmentMimeType)
                ?: error("ios_chat_attachment_mime_invalid")
            if (response.data.length.toLong() !in 1..MaxAttachmentBytes) {
                error("ios_chat_attachment_size_invalid")
            }
            val sourceName = displayName.safeChatAttachmentName()
                ?: canonicalUrl.substringAfterLast('/').safeChatAttachmentName()
                ?: "attachment"
            val destination = cacheDestination(sourceName)
            val destinationPath = destination.path ?: error("ios_chat_attachment_cache_path_missing")
            if (!response.data.writeToFile(destinationPath, atomically = true)) {
                error("ios_chat_attachment_cache_write_failed")
            }
            PlatformFile(
                reference = destination.absoluteString ?: destinationPath,
                displayName = sourceName,
                mimeType = mimeType,
                sizeBytes = response.data.length.toLong(),
            )
        }.fold(
            onSuccess = PlatformResult::Success,
            onFailure = { PlatformResult.Failure(it.message ?: "ios_chat_attachment_download_failed") },
        )
    }

    private fun cacheDestination(sourceName: String): NSURL {
        val manager = NSFileManager.defaultManager
        val cacheDirectory = NSTemporaryDirectory().trimEnd('/') + "/quata_chat_attachments"
        if (!manager.fileExistsAtPath(cacheDirectory) && !manager.createDirectoryAtPath(
                cacheDirectory,
                withIntermediateDirectories = true,
                attributes = null,
                error = null,
            )
        ) {
            error("ios_chat_attachment_cache_create_failed")
        }
        val extension = sourceName.substringAfterLast('.', missingDelimiterValue = "")
            .takeIf { it.matches(SafeExtension) }
            ?.let { ".${it.lowercase()}" }
            .orEmpty()
        val safeName = "${NSUUID.UUID().UUIDString.lowercase()}$extension"
        return NSURL.fileURLWithPath("$cacheDirectory/$safeName")
    }
}

private data class IosPublicChatAttachmentResponse(
    val data: NSData,
    val mimeType: String?,
)

@OptIn(ExperimentalForeignApi::class)
private suspend fun String.downloadPublicChatAttachment(): IosPublicChatAttachmentResponse =
    suspendCancellableCoroutine { continuation ->
        val url = NSURL(string = this) ?: run {
            continuation.resumeWithException(IllegalArgumentException("ios_chat_attachment_url_invalid"))
            return@suspendCancellableCoroutine
        }
        // Do not add Authorization, apikey or cookies: this is a validated public Storage URL.
        val request = NSMutableURLRequest.requestWithURL(url).apply {
            setHTTPMethod("GET")
            setValue(ChatAttachmentAcceptHeader, "Accept")
            setValue("no-store", "Cache-Control")
        }
        val delegate = IosPublicChatAttachmentDelegate(continuation)
        val session = NSURLSession.sessionWithConfiguration(
            NSURLSessionConfiguration.ephemeralSessionConfiguration(),
            delegate,
            null,
        )
        val task = session.dataTaskWithRequest(request)
        continuation.invokeOnCancellation {
            task.cancel()
            session.invalidateAndCancel()
        }
        task.resume()
    }

@OptIn(ExperimentalForeignApi::class)
private class IosPublicChatAttachmentDelegate(
    private val continuation: CancellableContinuation<IosPublicChatAttachmentResponse>,
) : NSObject(), NSURLSessionDataDelegateProtocol {
    private val chunks = mutableListOf<ByteArray>()
    private var bytesReceived = 0L
    private var terminalReason: String? = null
    private var redirectRejected = false

    override fun URLSession(session: NSURLSession, dataTask: NSURLSessionDataTask, didReceiveData: NSData) {
        if (!continuation.isActive || terminalReason != null) return
        val chunk = didReceiveData.toChatAttachmentBytes()
        if (chunk.size.toLong() > MaxAttachmentBytes - bytesReceived) {
            terminalReason = "ios_chat_attachment_size_invalid"
            dataTask.cancel()
            return
        }
        bytesReceived += chunk.size
        chunks += chunk
    }

    override fun URLSession(
        session: NSURLSession,
        task: NSURLSessionTask,
        willPerformHTTPRedirection: NSHTTPURLResponse,
        newRequest: NSURLRequest,
        completionHandler: (NSURLRequest?) -> Unit,
    ) {
        // Re-validating a redirect target would still turn a message attachment into a redirect
        // oracle. Public Chat objects are canonical and never need redirects, so fail closed.
        redirectRejected = true
        completionHandler(null)
    }

    override fun URLSession(session: NSURLSession, task: NSURLSessionTask, didCompleteWithError: NSError?) {
        session.finishTasksAndInvalidate()
        if (!continuation.isActive) return
        val failure = terminalReason
            ?: if (redirectRejected) "ios_chat_attachment_redirect_rejected" else null
        if (failure != null) {
            continuation.resumeWithException(IllegalStateException(failure))
            return
        }
        if (didCompleteWithError != null) {
            continuation.resumeWithException(IllegalStateException(didCompleteWithError.localizedDescription))
            return
        }
        val response = task.response ?: run {
            continuation.resumeWithException(IllegalStateException("ios_chat_attachment_response_missing"))
            return
        }
        val status = (response as? NSHTTPURLResponse)?.statusCode?.toInt()
        if (status == null || status !in 200..299) {
            continuation.resumeWithException(IllegalStateException("ios_chat_attachment_http_${status ?: "unknown"}"))
            return
        }
        val declaredLength = response.expectedContentLength
        if (declaredLength > MaxAttachmentBytes || bytesReceived !in 1..MaxAttachmentBytes) {
            continuation.resumeWithException(IllegalStateException("ios_chat_attachment_size_invalid"))
            return
        }
        continuation.resume(
            IosPublicChatAttachmentResponse(
                data = chunks.toChatAttachmentData(),
                mimeType = response.MIMEType,
            ),
        )
    }
}

@OptIn(ExperimentalForeignApi::class)
private fun NSData.toChatAttachmentBytes(): ByteArray =
    if (length == 0uL) ByteArray(0) else bytes?.readBytes(length.toInt()) ?: ByteArray(0)

@OptIn(ExperimentalForeignApi::class)
private fun List<ByteArray>.toChatAttachmentData(): NSData {
    val merged = ByteArray(bytesReceivedSize())
    var offset = 0
    forEach { chunk ->
        chunk.copyInto(merged, destinationOffset = offset)
        offset += chunk.size
    }
    return merged.toIosData()
}

private fun List<ByteArray>.bytesReceivedSize(): Int = sumOf(ByteArray::size)

@OptIn(ExperimentalForeignApi::class)
private fun ByteArray.toIosData(): NSData = usePinned { pinned ->
    CFDataCreate(null, pinned.addressOf(0).reinterpret(), size.toLong())!! as NSData
}

private fun String?.normalisedChatMimeType(): String? = this
    ?.substringBefore(';')
    ?.trim()
    ?.lowercase()
    ?.takeIf(String::isNotEmpty)

private fun isAllowedChatAttachmentMimeType(value: String): Boolean =
    value.startsWith("image/") || value.startsWith("audio/") || value.startsWith("video/") ||
        value in AllowedDocumentMimeTypes

private fun String?.safeChatAttachmentName(): String? = this
    ?.trim()
    ?.substringAfterLast('/')
    ?.substringAfterLast('\\')
    ?.takeIf { it.length in 1..128 && SafeAttachmentName.matches(it) }

private const val MaxAttachmentBytes = 50L * 1024L * 1024L
private const val ChatAttachmentAcceptHeader = "image/*,audio/*,video/*,application/pdf,text/plain,text/rtf,application/rtf,application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document,application/vnd.ms-excel,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,application/vnd.ms-powerpoint,application/vnd.openxmlformats-officedocument.presentationml.presentation"
private val SafeAttachmentName = Regex("[A-Za-z0-9._-]+")
private val SafeExtension = Regex("[A-Za-z0-9]{1,16}")
private val AllowedDocumentMimeTypes = setOf(
    "application/pdf",
    "text/plain",
    "text/rtf",
    "application/rtf",
    "application/msword",
    "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    "application/vnd.ms-excel",
    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    "application/vnd.ms-powerpoint",
    "application/vnd.openxmlformats-officedocument.presentationml.presentation",
)
