import { readFile } from "node:fs/promises";
import test from "node:test";
import assert from "node:assert/strict";

const source = (path) => readFile(path, "utf8");

test("chat actions/notifications web evidence keeps credentials private and reversible", async () => {
  const runner = await source("scripts/chat-actions-notifications-web-evidence.mjs");
  assert.match(runner, /QUATA_CHAT_ACTIONS_NOTIFICATIONS_CREDENTIALS_FILE/);
  assert.match(runner, /QUATA_CHAT_ACTIONS_NOTIFICATIONS_USE_ADJACENT_AUTHORIZED_PROFILE/);
  assert.match(runner, /QUATA_CHAT_ACTIONS_NOTIFICATIONS_SSH_CREDENTIALS_FILE/);
  assert.doesNotMatch(runner, /680242607|680242608|21085800/);
  assert.match(runner, /qadata-chat-actions-notifications-/);
  assert.match(runner, /QUATA_CHAT_ACTIONS_NOTIFICATIONS_HARD_CLEANUP_AUTHORIZATION/);
  assert.match(runner, /QUATA_CHAT_ACTIONS_NOTIFICATIONS_CREDENTIALS_FILE/);
  assert.match(runner, /MANAGER_APPROVED_QADATA_CHAT_ACTIONS_NOTIFICATIONS_HARD_CLEANUP/);
  assert.match(runner, /begin/);
  assert.match(runner, /for update/);
  assert.match(runner, /delete from public\.chat_threads where id = \$1 and unique_key = \$2 returning id/);
  assert.match(runner, /cleanup_verified_physical_residue_absent/);
  assert.match(runner, /createTemporaryForwardProfile/);
  assert.match(runner, /hardDeleteTemporaryForwardDestination/);
  assert.match(runner, /forward_destination_cleanup_verified_physical_residue_absent/);
  assert.match(runner, /--profile-follow-only/);
  assert.match(runner, /--profile-private-chat-only/);
  assert.match(runner, /prepareProfileFollowAbsent/);
  assert.match(runner, /pollProfileFollowEdge/);
  assert.match(runner, /restoreProfileFollowEdge/);
  assert.match(runner, /profile_follow_edge_restored_to_initial_state/);
});

test("chat actions/notifications Android evidence keeps backend fixture reversible", async () => {
  const runner = await source("scripts/chat-actions-notifications-android-evidence.mjs");
  const testSource = await source("app/src/androidTest/java/com/quata/feature/chat/presentation/chat/ChatActionsNotificationsInstrumentedTest.kt");
  assert.match(runner, /QUATA_CHAT_ACTIONS_NOTIFICATIONS_HARD_CLEANUP_AUTHORIZATION/);
  assert.match(runner, /MANAGER_APPROVED_QADATA_CHAT_ACTIONS_NOTIFICATIONS_HARD_CLEANUP/);
  assert.match(runner, /QUATA_CHAT_ACTIONS_NOTIFICATIONS_TEMP_PROFILE_HASH_AUTHORIZATION/);
  assert.match(runner, /MANAGER_APPROVED_QADATA_CHAT_ACTIONS_NOTIFICATIONS_TEMP_PROFILE_HASH/);
  assert.match(runner, /action: "login"/);
  assert.doesNotMatch(runner, /action: "web_login"/);
  assert.doesNotMatch(runner, /680242607|680242608|21085800/);
  assert.match(runner, /qadata-chat-actions-notifications-android-/);
  assert.match(runner, /select id, pass_hash, pass_plain[\s\S]*for update/);
  assert.match(runner, /update public\.community_profiles set pass_hash = \$1, pass_plain = null where id = \$2/);
  assert.match(runner, /update public\.community_profiles set pass_hash = \$1, pass_plain = \$2 where id = \$3/);
  assert.match(runner, /delete from public\.chat_threads where id = \$1 and unique_key = \$2 returning id/);
  assert.match(runner, /cleanup_verified_physical_residue_absent/);
  assert.match(runner, /createTemporaryForwardProfile/);
  assert.match(runner, /hardDeleteTemporaryForwardDestination/);
  assert.match(runner, /forward_destination_cleanup_verified_physical_residue_absent/);
  assert.match(runner, /ChatActionsNotificationsInstrumentedTest/);
  assert.match(runner, /function resolveAdbCommand\(\)/);
  assert.match(runner, /process\.env\.ADB/);
  assert.match(runner, /process\.env\.ANDROID_HOME/);
  assert.match(runner, /process\.env\.ANDROID_SDK_ROOT/);
  assert.match(runner, /process\.env\.LOCALAPPDATA/);
  assert.doesNotMatch(runner, /run\("adb"/);
  assert.doesNotMatch(runner, /runCapture\("adb"/);
  assert.doesNotMatch(runner, /spawn\("adb"/);
  assert.match(runner, /--profile-follow-only/);
  assert.match(runner, /--menu-surface-only/);
  assert.match(runner, /--group-sos-only/);
  assert.match(runner, /--group-moderation-only/);
  assert.match(runner, /assertInstrumentationPassed\("menu-surface", await runInstrumentationStage\("menu-surface"\)\)/);
  assert.match(runner, /assertInstrumentationPassed\("group-sos", await runInstrumentationStage\("group-sos"\)\)/);
  assert.match(runner, /assertInstrumentationPassed\("group-moderation", await runInstrumentationStage\("group-moderation"\)\)/);
  assert.match(runner, /android-chat-options-menu-surface/);
  assert.match(runner, /android-chat-group-menu-shared-anchors/);
  assert.match(runner, /android-chat-sos-location-map-return/);
  assert.match(runner, /options_menu_surface_visible_and_mute_toggled_by_shared_ui/);
  assert.match(runner, /group_menu_and_sos_shared_anchors_verified/);
  assert.match(runner, /prepareProfileFollowAbsent/);
  assert.match(runner, /pollProfileFollowEdge/);
  assert.match(runner, /restoreProfileFollowEdge/);
  assert.match(runner, /profile_follow_edge_restored_to_initial_state/);
  assert.match(runner, /QUATA_CHAT_ACTIONS_NOTIFICATIONS_TRANSLATION_ONLY/);
  assert.match(runner, /android-chat-translation-overlay/);
  assert.match(runner, /android-chat-translation-result/);
  assert.match(runner, /android-chat-translation-return/);
  assert.match(runner, /assertInstrumentationPassed\("translation", await runInstrumentationStage\("translation"\)\)/);
  assert.match(runner, /chat_translation_common_overlay_translated_fang_message_and_returned/);
  assert.match(runner, /composer_text_sent_by_shared_ui_and_verified_by_rpc/);
  assert.match(runner, /composer_reply_sent_by_shared_ui_and_verified_by_rpc/);
  assert.match(runner, /composer_edit_sent_by_shared_ui_and_verified_by_rpc/);
  assert.match(runner, /favorite_toggled_and_verified_by_rpc/);
  assert.match(testSource, /ChatComposerInputTestTag/);
  assert.match(testSource, /runTranslationStage/);
  assert.match(testSource, /ChatTranslatorTriggerTestTag/);
  assert.match(testSource, /ChatTranslatorOverlayTestTag/);
  assert.match(testSource, /ChatTranslatorMessageTestTagPrefix/);
  assert.match(testSource, /android-chat-translation-result/);
  assert.match(testSource, /ChatComposerSendTestTag/);
  assert.match(testSource, /chat\.action\.reply/);
  assert.match(testSource, /chat\.action\.edit/);
  assert.match(testSource, /chat\.action\.favorite/);
  assert.match(testSource, /chat\.action\.forward/);
  assert.match(testSource, /ChatGroupMenuOptionsTestTag/);
  assert.match(testSource, /runMenuSurfaceStage/);
  assert.match(testSource, /runGroupSosStage/);
  assert.match(testSource, /runGroupModerationStage/);
  assert.match(testSource, /ChatGroupMemberRemoveTestTagPrefix/);
  assert.match(testSource, /ChatGroupMemberBlockTestTagPrefix/);
  assert.match(testSource, /android-chat-options-menu-surface/);
  assert.match(testSource, /ChatGroupMenuAllowInvitesTestTag/);
  assert.match(testSource, /ChatSosLocationMapPreviewTestTag/);
  assert.match(testSource, /ChatSosLocationUnavailableTestTag/);
  assert.match(testSource, /ChatForwardPickerSearchTestTag/);
  assert.match(testSource, /ChatForwardPickerSendTestTag/);
  assert.match(testSource, /android-chat-actions-own-selected/);
  assert.match(testSource, /android-chat-forward-picker-selected/);
  assert.match(testSource, /android-chat-forward-submitted/);
  assert.match(testSource, /public-profile\.avatar\.\$profileId/);
  assert.match(testSource, /public-profile\.name\.\$profileId/);
  assert.match(testSource, /public-profile\.neighborhood\.\$profileId/);
  assert.match(testSource, /public-profile\.kpi\.posts\.\$profileId/);
  assert.match(testSource, /public-profile\.kpi\.followers\.\$profileId/);
  assert.match(testSource, /public-profile\.kpi\.following\.\$profileId/);
  assert.match(testSource, /profile-follow/);
  assert.match(testSource, /public-profile\.follow\.\$profileId/);
  assert.match(testSource, /public-profile\.chat\.\$profileId/);
  assert.match(testSource, /android-chat-profile-follow-after/);
  assert.match(testSource, /android-chat-profile-private-chat-opened/);
});

test("chat actions/notifications iOS evidence forwards through the shared picker", async () => {
  const runner = await source("scripts/chat-actions-notifications-ios-evidence.mjs");
  const wrapper = await source("scripts/run-ios-chat-actions-notifications-ui-test.sh");
  const testSource = await source("iosApp/iosAppUITests/QuataIosAuthenticatedChatActionsNotificationsUITests.swift");
  assert.match(runner, /QUATA_IOS_CHAT_E2E_FORWARD_QUERY/);
  assert.match(wrapper, /QUATA_IOS_CHAT_E2E_FORWARD_QUERY/);
  assert.match(runner, /createTemporaryForwardProfile/);
  assert.match(runner, /pollForwardDestinationThread/);
  assert.match(runner, /message_forwarded_by_shared_ui_and_verified_by_rpc/);
  assert.match(runner, /hardDeleteTemporaryForwardDestination/);
  assert.match(runner, /forward_destination_cleanup_verified_physical_residue_absent/);
  assert.match(runner, /--profile-follow-only/);
  assert.match(runner, /--profile-private-chat-only/);
  assert.match(runner, /--menu-surface-only/);
  assert.match(runner, /--group-sos-only/);
  assert.match(runner, /--group-moderation-only/);
  assert.match(runner, /QUATA_IOS_CHAT_OPTIONS_MENU_SURFACE_UI_E2E/);
  assert.match(runner, /QUATA_IOS_CHAT_GROUP_SOS_UI_E2E/);
  assert.match(runner, /QUATA_IOS_CHAT_GROUP_MODERATION_UI_E2E/);
  assert.match(runner, /options_menu_surface_visible_from_shared_ui/);
  assert.match(runner, /ios_xctest_group_menu_and_sos_shared_anchors_verified/);
  assert.match(wrapper, /testOptionsMenuSurfaceUsesSharedOpaqueHeaderSurface/);
  assert.match(wrapper, /testGroupMenuAndSosMessagesExposeSharedAnchors/);
  assert.match(wrapper, /testGroupModerationRemovesAndBlocksParticipantsThroughSharedMemberMenu/);
  assert.match(wrapper, /group-sos\.log/);
  assert.match(testSource, /dismissOptionsMenu/);
  assert.match(testSource, /The group options menu must be dismissed before validating SOS anchors/);
  assert.match(runner, /--keyboard-menu-only/);
  assert.match(runner, /QUATA_IOS_CHAT_KEYBOARD_MENU_UI_E2E/);
  assert.match(runner, /keyboard_header_and_selected_action_bar_captured/);
  assert.match(runner, /report\.status = "failed";/);
  assert.match(runner, /keyboardMenuOnly,/);
  assert.match(wrapper, /testKeyboardAndSelectedActionBarUseSharedChatChrome/);
  assert.match(wrapper, /keyboard-menu\.log/);
  assert.match(runner, /QUATA_IOS_CHAT_PROFILE_FOLLOW_UI_E2E/);
  assert.match(runner, /QUATA_IOS_CHAT_PROFILE_PRIVATE_CHAT_UI_E2E/);
  assert.match(runner, /prepareProfileFollowAbsent/);
  assert.match(runner, /pollProfileFollowEdge/);
  assert.match(runner, /restoreProfileFollowEdge/);
  assert.match(runner, /profile_follow_edge_restored_to_initial_state/);
  assert.match(testSource, /chat\.action\.forward/);
  assert.match(testSource, /chat\.forward\.root/);
  assert.match(testSource, /chat\.forward\.search/);
  assert.match(testSource, /ios-chat-forward-picker-selected/);
  assert.match(testSource, /chat\.forward\.send/);
  assert.match(runner, /QUATA_CHAT_EVIDENCE_PAIR_FROM_SINGLE_FILE/);
  assert.match(runner, /QUATA_CHAT_ACTIONS_NOTIFICATIONS_IOS_USE_ADJACENT_AUTHORIZED_PROFILE/);
  assert.match(runner, /QUATA_CHAT_ACTIONS_NOTIFICATIONS_IOS_SSH_CREDENTIALS_FILE/);
  assert.match(runner, /async function authorizedUsersFromAdjacentSshCredential\(\)/);
  assert.match(runner, /function authorizedPairFromSingleCredential\(entry\)/);
  assert.match(runner, /scripts\/ios-public-client-config\.py/);
  assert.match(runner, /QuataPublicRuntime\.local\.xcconfig/);
  assert.doesNotMatch(runner, /680242607|680242608|21085800/);
  assert.match(testSource, /public-profile\.avatar\.\\\(peerProfileId\)/);
  assert.match(testSource, /public-profile\.name\.\\\(peerProfileId\)/);
  assert.match(testSource, /public-profile\.neighborhood\.\\\(peerProfileId\)/);
  assert.match(testSource, /public-profile\.kpi\.posts\.\\\(peerProfileId\)/);
  assert.match(testSource, /public-profile\.kpi\.followers\.\\\(peerProfileId\)/);
  assert.match(testSource, /public-profile\.kpi\.following\.\\\(peerProfileId\)/);
  assert.match(testSource, /testProfileFollowFromChatTogglesSharedPublicProfileAction/);
  assert.match(testSource, /public-profile\.follow\.\\\(peerProfileId\)/);
  assert.match(testSource, /public-profile\.chat\.\\\(peerProfileId\)/);
  assert.match(testSource, /ios-chat-profile-follow-after/);
  assert.match(testSource, /ios-chat-profile-private-chat-opened/);
  assert.match(testSource, /chat\.menu\.options/);
  assert.match(testSource, /ios-chat-options-menu-surface/);
  assert.match(testSource, /chat\.group\.menu\.allowInvites/);
  assert.match(testSource, /chat\.sos\.location\.mapPreview/);
  assert.match(testSource, /chat\.group\.member\.remove\.\\\(removeProfileId\)/);
  assert.match(testSource, /chat\.group\.member\.block\.\\\(blockProfileId\)/);
  assert.match(testSource, /ios-chat-group-moderation-member-removed/);
  assert.match(testSource, /ios-chat-group-moderation-member-blocked/);
  assert.match(testSource, /ios-chat-sos-location-map-return/);
  assert.match(testSource, /chat\.sos\.location\.openMaps/);
  assert.match(testSource, /Abriendo ubicación en mapas\./);
  assert.match(testSource, /testKeyboardAndSelectedActionBarUseSharedChatChrome/);
  assert.match(testSource, /assertConversationHeaderVisibleWithKeyboard\(in: app\)/);
  assert.match(testSource, /ios-chat-keyboard-header-visible/);
  assert.match(testSource, /ios-chat-selected-action-bar-opaque/);
});

test("chat actions/notifications iOS evidence can run translation-only against the shared overlay", async () => {
  const runner = await source("scripts/chat-actions-notifications-ios-evidence.mjs");
  const wrapper = await source("scripts/run-ios-chat-translation-ui-test.sh");
  const testSource = await source("iosApp/iosAppUITests/QuataIosAuthenticatedChatTranslationUITests.swift");
  assert.match(runner, /--translation-only/);
  assert.match(runner, /state\.seedMarker = translationOnly \? "Mbolo"/);
  assert.match(runner, /bash scripts\/run-ios-chat-translation-ui-test\.sh/);
  assert.match(runner, /ios_xctest_chat_translation_common_overlay_verified/);
  assert.match(wrapper, /QUATA_IOS_AUTH_UI_E2E/);
  assert.match(wrapper, /QuataIosAuthenticatedChatTranslationUITests\/testRealChatMessageTranslatesAndReturnsToTheConversation/);
  assert.match(testSource, /openDeepLink\("quata:\/\/egquata\.com\/#chat-/);
  assert.match(testSource, /chat-translation-result/);
});

test("chat actions/notifications web evidence exercises real shared chat controls", async () => {
  const runner = await source("scripts/chat-actions-notifications-web-evidence.mjs");
  assert.match(runner, /quata_chat_start_thread/);
  assert.match(runner, /quata_chat_send_message/);
  assert.match(runner, /quata_chat_set_muted/);
  assert.match(runner, /quata_chat_get_inbox/);
  assert.match(runner, /quata_chat_get_favorites/);
  assert.match(runner, /quata_chat_get_or_create_private_thread|pollForwardDestinationThread/);
  assert.match(runner, /message_forwarded_by_shared_ui_and_verified_by_rpc/);
  assert.match(runner, /const ownMarker = options\.translationOnly \? "Mbolo" : `chat-actions-own-\$\{runId\}`/);
  assert.match(runner, /--translation-only/);
  assert.match(runner, /--menu-surface-only/);
  assert.match(runner, /--group-sos-only/);
  assert.match(runner, /--group-admin-only/);
  assert.match(runner, /--group-moderation-only/);
  assert.match(runner, /group_participant_removed_from_shared_member_menu_and_verified_by_db/);
  assert.match(runner, /group_participant_blocked_from_shared_member_menu_and_verified_by_db/);
  assert.match(runner, /async function verifyChatOptionsMenuSurface\(page, config, state, evidenceDir, report\)/);
  assert.match(runner, /async function verifyChatGroupSosWeb\(page, evidenceDir, report\)/);
  assert.match(runner, /async function verifyChatGroupAdminWeb\(page, state, evidenceDir, report\)/);
  assert.match(runner, /temporary_group_admin_participant_profile_created/);
  assert.match(runner, /group_admin_actor_seeded_as_moderator_for_ui_management/);
  assert.match(runner, /group_admin_ui_session_opened_as_peer_moderator/);
  assert.match(runner, /chat\.group\.participants\.candidate\./);
  assert.match(runner, /group_participant_search_used_visual_fallback/);
  assert.match(runner, /group_participant_confirm_used_visual_fallback/);
  assert.match(runner, /group_thread_reopened_after_participant_add_for_fresh_membership/);
  assert.match(runner, /chat\.group\.member\.manage\./);
  assert.match(runner, /group_member_manage_used_visual_fallback/);
  assert.match(runner, /chat\.group\.member\.role\./);
  assert.match(runner, /Ascender a moderador/);
  assert.match(runner, /async function visibleTextBoxMatching\(page, patterns\)/);
  assert.match(runner, /group_participant_added_from_shared_picker_and_verified_by_db/);
  assert.match(runner, /group_participant_promoted_from_shared_member_menu_and_verified_by_db/);
  assert.match(runner, /web-chat-options-menu-surface/);
  assert.match(runner, /web-chat-group-menu-shared-anchors/);
  assert.match(runner, /web-chat-group-admin-participant-picker/);
  assert.match(runner, /web-chat-group-admin-member-menu/);
  assert.match(runner, /web-chat-group-admin-member-promoted/);
  assert.match(runner, /web-chat-sos-location-map-return/);
  assert.match(runner, /reason=permission_denied/);
  assert.match(runner, /sos_permission_denied_reason_not_visible/);
  assert.match(runner, /async function closeOptionsMenu\(page, report, context\)/);
  assert.match(runner, /await page\.reload\(\{ waitUntil: "domcontentloaded" \}\)/);
  assert.match(runner, /group_sos_options_menu_reset_by_route_after_anchor_evidence/);
  assert.match(runner, /options_menu_closed_by_semantic_mute_action/);
  assert.match(runner, /options_menu_did_not_close/);
  assert.match(runner, /missing_stable_anchor/);
  assert.match(runner, /sos_map_open_feedback_not_visible/);
  assert.match(runner, /No se pudo abrir la ubicación\./);
  assert.match(runner, /No hay una aplicación de mapas disponible\./);
  assert.match(runner, /chat\.sos\.location\.openMaps/);
  assert.match(runner, /wasmCanvasSemanticLimit/);
  assert.match(runner, /options_menu_surface_visible_and_mute_enabled_by_rpc/);
  assert.match(runner, /group_menu_and_sos_shared_anchors_verified/);
  assert.match(runner, /if \(options\.menuSurfaceOnly\) \{/);
  assert.match(runner, /--profile-follow-only/);
  assert.match(runner, /--profile-private-chat-only/);
  assert.match(runner, /toggleFollowFromOpenProfile/);
  assert.match(runner, /openPrivateChatFromOpenProfile/);
  assert.match(runner, /createPrivateChatSeed/);
  assert.match(runner, /quata_chat_get_or_create_private_thread/);
  assert.match(runner, /profile_private_chat_seed_message_ready/);
  assert.match(runner, /profile_private_chat_opened_from_common_profile_action_and_verified_by_rpc/);
  assert.match(runner, /pollMessage\(config, state\.a, privateChat\.threadId/);
  assert.match(runner, /waitForExactChatRoute\(page, `sb:\$\{privateChat\.threadId\}`\)/);
  assert.match(runner, /profile_private_chat_marker_deleted/);
  assert.match(runner, /cleanup_verified_profile_private_chat_marker_absent/);
  assert.match(runner, /web-chat-profile-private-chat-opened/);
  assert.doesNotMatch(runner, /viewport\.width \* 0\.72/);
  assert.doesNotMatch(runner, /openAuthenticatedChatRoute\(page, serverOrigin, `sb:\$\{opened\.threadId\}`\)/);
  for (const platformRunner of [
    await source("scripts/chat-actions-notifications-android-evidence.mjs"),
    await source("scripts/chat-actions-notifications-ios-evidence.mjs"),
  ]) {
    assert.match(platformRunner, /profile_private_chat_marker_deleted/);
    assert.match(platformRunner, /cleanup_verified_profile_private_chat_marker_absent/);
    assert.match(platformRunner, /profilePrivateChatMarkerMessage/);
    assert.match(platformRunner, /options_menu_(surface_visible_and_mute_enabled_by_rpc|surface_visible_and_mute_toggled_by_shared_ui|surface_visible_from_shared_ui)/);
    assert.match(platformRunner, /options_menu_unmute_verified_by_rpc/);
  }
  assert.match(runner, /profile_follow_toggled_and_verified_by_db/);
  assert.match(runner, /profile_follow_edge_restored_to_initial_state/);
  assert.match(runner, /class EvidenceCompleted extends Error/);
  assert.match(runner, /if \(options\.translationOnly\) \{/);
  assert.match(runner, /const translationMarker = state\.peerMessage \? peerMarker : ownMarker/);
  assert.match(runner, /function isProfileFocalMode\(options\)/);
  assert.match(runner, /function isFullEvidenceMode\(options\)/);
  assert.match(runner, /if \(options\.translationOnly \|\| \(isFullEvidenceMode\(options\) && state\.peerMessage\)\) \{/);
  assert.doesNotMatch(runner, /!\s*options\.menuSurfaceOnly && !\s*options\.attachmentsAudioOnly && state\.peerMessage/);
  assert.match(runner, /verifyChatTranslation\(page, options\.evidenceDir, translationMarker\)/);
  assert.match(runner, /async function verifyChatTranslation\(page, evidenceDir, marker\)/);
  assert.match(runner, /async function clickTranslatorOverlayMessage\(page, marker\)/);
  assert.match(runner, /role === "button" && label\.includes\(" \| "\) && label\.includes\(needle\)/);
  assert.match(runner, /waitMessageVisible\(page, "pan de trigo", "translator_result_not_visible", 90_000\)/);
  assert.match(runner, /waitMessageVisible\(page, "FAN->ES", "translator_direction_not_visible"/);
  assert.match(runner, /chat_translation_common_overlay_translated_fang_message_and_returned/);
  assert.match(runner, /web-chat-forward-picker-selected/);
  assert.match(runner, /web-chat-forwarded-message/);
  assert.match(runner, /async function clickMessage\(page, marker, error\)/);
  assert.match(runner, /async function openMessageActions\(page, marker, expectedPatterns, targetError, actionError\)/);
  assert.match(runner, /if \(marker\.startsWith\("chat-edit-ui-"\)\) \{/);
  assert.match(runner, /async function longPressMessage\(page, marker\)/);
  assert.match(runner, /async function waitMessageVisible\(page, marker, error, timeout = 45_000\)/);
  assert.match(runner, /async function visibleTextContentIncludes\(page, probe\)/);
  assert.match(runner, /String\(value \?\? ""\)\.replace\(\/\\s\+\/g, ""\)/);
  assert.match(runner, /if \(await visibleTextContentIncludes\(page, probe\)\) return/);
  assert.match(runner, /const profileSheetVisible = controls\.some\(\(control\) => \/Cerrar hoja\|Close sheet\|Controlador de arrastre\|Drag handle\/i\.test\(control\.label\)\)/);
  assert.match(runner, /if \(composerVisible && !profileSheetVisible\) return true/);
  assert.match(runner, /async function closeProfileSheetIfVisible\(page\)/);
  assert.match(runner, /visibleAriaLocator\(page, \[\/Cerrar hoja\|Close sheet\/i\], 1_000\)/);
  assert.match(runner, /await closeProfileSheetIfVisible\(page\)/);
  assert.match(runner, /async function assertProfileHeaderVisible\(page, profile\)/);
  assert.match(runner, /profile_header_name_missing/);
  assert.match(runner, /profile_header_neighborhood_missing/);
  assert.match(runner, /profile_header_kpi_missing/);
  assert.match(runner, /async function clickMessageProbe\(page, probe\)/);
  assert.match(runner, /marker\.slice\(0, 28\), marker\.slice\(0, 20\), marker\.slice\(0, 16\)/);
  assert.match(runner, /marker\.startsWith\("chat-edit-ui-"\)/);
  assert.match(runner, /marker\.startsWith\("chat-actions-own-"\)/);
  assert.match(runner, /page\.mouse\.click\(Math\.round\(viewport\.width \* 0\.62\), 214\)/);
  assert.match(runner, /async function visibleTextBox\(page, probe\)/);
  assert.match(runner, /async function clickNativeButtonByLabel\(page, patterns\)/);
  assert.match(runner, /async function visibleAriaLocator\(page, patterns, timeout\)/);
  assert.match(runner, /async function clickOptionsMenu\(page\)/);
  assert.match(runner, /async function clickFavoriteAction\(page\)/);
  assert.match(runner, /page\.mouse\.click\(Math\.max\(1, viewport\.width - 26\), 104\)/);
  assert.match(runner, /page\.locator\("\[aria-label\]"\)/);
  assert.match(runner, /getByRole\("button", \{ name: pattern \}/);
  assert.match(runner, /await text\.scrollIntoViewIfNeeded\(\{ timeout: 5_000 \}\)/);
  assert.match(runner, /const box = await text\.boundingBox\(\)/);
  assert.match(runner, /page\.mouse\.click\(Math\.max\(1, box\.x - 12\), box\.y \+ \(box\.height \/ 2\)\)/);
  assert.match(runner, /const textBox = await visibleTextBox\(page, probe\)/);
  assert.match(runner, /sort\(\(left, right\) => left\.area - right\.area \|\| left\.textLength - right\.textLength \|\| left\.y - right\.y\)/);
  assert.match(runner, /fillComposerAndSend\(page, composerMarker\)/);
  assert.match(runner, /await waitMessageVisible\(page, composerMarker, "composer_message_not_visible"\)/);
  assert.match(runner, /const input = await visibleAriaLocator\(page, \[\/Mensaje\|Message\|Composer\/i\], 10_000\)/);
  assert.match(runner, /const deadline = Date\.now\(\) \+ 10_000/);
  assert.match(runner, /let sawSend = false/);
  assert.match(runner, /const send = await visibleAriaLocator\(page, \[\/Enviar\|Send\/i\], 1_000\)/);
  assert.match(runner, /if \(!sawSend\) throw new Error\("composer_send_not_visible"\)/);
  assert.match(runner, /input\.inputValue\(\)\.then\(\(current\) => current === value\)/);
  assert.match(runner, /page\.mouse\.click\(box\.x \+ \(box\.width \/ 2\), box\.y \+ \(box\.height \/ 2\)\)/);
  assert.match(runner, /await clickNativeButtonByLabel\(page, \[\/Enviar\|Send\/i\]\)/);
  assert.match(runner, /throw new Error\("composer_send_not_dispatched"\)/);
  assert.match(runner, /await fillComposerAndSend\(page, editMarker\)/);
  assert.match(runner, /composer_text_sent_by_shared_ui_and_verified_by_rpc/);
  assert.match(runner, /report\.evidence\.replySent = await attachScreenshot\(page, options\.evidenceDir, "web-chat-composer-reply-sent"\)/);
  assert.match(runner, /const replyTargetMessageId = state\.peerMessage \?\? state\.ownMessage/);
  assert.match(runner, /messageReplyToId\(message\) === Number\(replyTargetMessageId\)/);
  assert.match(runner, /composer_reply_sent_by_shared_ui_and_verified_by_rpc/);
  assert.match(runner, /safeErrorMessage: error\.message/);
  assert.match(runner, /state\.editableUiMessage = composerMessageId/);
  assert.match(runner, /await openMessageActions\(page, ownMarker, \[\/Editar\|Edit\/i\], "message_action_target_not_clickable:edit", "action_bar_not_visible:edit"\)/);
  assert.match(runner, /Number\(state\.ownMessage\) && messageText\(message\) === editMarker/);
  assert.match(runner, /report\.evidence\.editSent = await attachScreenshot\(page, options\.evidenceDir, "web-chat-composer-edit-sent"\)/);
  assert.match(runner, /await openMessageActions\(page, editMarker, \[\/Copiar mensaje\|Copiar texto\|Copy message\|Copy text\/i\], "message_action_target_not_clickable:own_actions", "action_bar_not_visible:copy"\)/);
  assert.match(runner, /report\.evidence\.ownActions = await attachScreenshot\(page, options\.evidenceDir, "web-chat-actions-own-selected"\)/);
  assert.match(runner, /await clickFavoriteAction\(page\)/);
  assert.match(runner, /page\.mouse\.click\(Math\.max\(1, viewport\.width - 66\), 98\)/);
  assert.match(runner, /Number\(message\?\.id\) === Number\(state\.ownMessage\)/);
  assert.match(runner, /composer_edit_sent_by_shared_ui_and_verified_by_rpc/);
  assert.match(runner, /clickOptionsMenu\(page\)/);
  assert.match(runner, /getByText\(\/Silenciar conversaci\[oó\]n\|Mute conversation\/i\)/);
  assert.match(runner, /favorite_toggled_and_verified_by_rpc/);
  for (const screenshot of [
    "web-chat-actions-thread-initial",
    "web-chat-translation-overlay",
    "web-chat-translation-result",
    "web-chat-translation-return",
    "web-chat-composer-sent",
    "web-chat-composer-reply-sent",
    "web-chat-composer-edit-sent",
    "web-chat-actions-muted",
    "web-chat-actions-own-selected",
    "web-chat-actions-peer-selected",
    "web-chat-forward-picker-selected",
    "web-chat-forwarded-message",
    "web-chat-profile-follow-before",
    "web-chat-profile-follow-after",
  ]) {
    assert.match(runner, new RegExp(screenshot));
  }
});
