import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { readFileSync, statSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('..', import.meta.url));
const drawable = join(root, 'designsystem/src/commonMain/composeResources/drawable');
const manifest = JSON.parse(readFileSync(join(root, 'tools/community_emoji_atlases.manifest.json'), 'utf8'));
const panel = readFileSync(join(root, 'designsystem/src/commonMain/kotlin/com/quata/core/ui/components/CommunityEmojiPanelContent.kt'), 'utf8');
const catalog = readFileSync(join(root, 'designsystem/src/commonMain/kotlin/com/quata/core/ui/components/CommunityEmojiCatalog.kt'), 'utf8');
const catalogTest = readFileSync(join(root, 'designsystem/src/commonTest/kotlin/com/quata/core/ui/components/CommunityEmojiCatalogTest.kt'), 'utf8');
const commentInput = readFileSync(join(root, 'designsystem/src/commonMain/kotlin/com/quata/core/ui/components/QuataCommentInputContent.kt'), 'utf8');
const commentTextFieldExpect = readFileSync(join(root, 'designsystem/src/commonMain/kotlin/com/quata/core/ui/components/QuataEmojiCommentTextField.kt'), 'utf8');
const commentTextFieldAndroid = readFileSync(join(root, 'designsystem/src/androidMain/kotlin/com/quata/core/ui/components/QuataEmojiCommentTextField.android.kt'), 'utf8');
const commentTextFieldIos = readFileSync(join(root, 'designsystem/src/iosMain/kotlin/com/quata/core/ui/components/QuataEmojiCommentTextField.ios.kt'), 'utf8');
const commentTextFieldWasm = readFileSync(join(root, 'designsystem/src/wasmJsMain/kotlin/com/quata/core/ui/components/QuataEmojiCommentTextField.wasm.kt'), 'utf8');
const androidPanel = readFileSync(join(root, 'app/src/main/java/com/quata/core/ui/components/CommunityEmojiPanel.kt'), 'utf8');

assert.equal(manifest.notoEmojiCommit, '8998f5dd683424a73e2314a8c1f1e359c19e8742');
assert.match(manifest.license, /^Apache-2\.0/);
assert.deepEqual(manifest.encoding, { format: 'PNG', paletteColors: 64 });
assert.deepEqual(Object.keys(manifest.sections), ['recent', 'frequent', 'gestures', 'people', 'animals_nature', 'food_drink', 'objects_symbols', 'flags']);
assert.equal(Object.values(manifest.sections).flatMap(section => section.emojis).length, 338);

for (const section of Object.values(manifest.sections)) {
  const file = join(drawable, section.file);
  assert.ok(statSync(file).size > 0, `${section.file} must not be empty`);
  assert.equal(createHash('sha256').update(readFileSync(file)).digest('hex'), section.sha256, `${section.file} hash mismatch`);
  assert.equal(section.columns, 6);
  assert.equal(section.cellPx, 72);
  assert.equal(section.paletteColors, 64);
}

assert.match(panel, /imageResource\(selectedAtlasLayout\.resource\)/);
assert.match(panel, /drawImage\(/);
assert.doesNotMatch(panel, /Text\(emoji[,) ]/);
assert.match(panel, /CommunityEmojiPanelRootTestTag/);
assert.match(panel, /CommunityEmojiPanelSectionsRowTestTag/);
assert.match(panel, /CommunityEmojiPanelGridTestTagPrefix/);
assert.match(panel, /CommunityEmojiPanelEmptyTestTag/);
assert.match(panel, /CommunityEmojiPanelErrorTestTag/);
assert.match(panel, /CommunityEmojiPanelRetryTestTag/);
assert.match(catalog, /val empty: String = "No hay emojis disponibles\."/);
assert.match(panel, /emptyMessage: String = CommunityEmojiLabels\(\)\.empty/);
assert.match(panel, /errorMessage: String\? = null/);
assert.match(catalog, /val retry: String = "Reintentar"/);
assert.match(catalog, /sealed interface CommunityEmojiCatalogState/);
assert.match(catalog, /data class Available\(val sections: List<QuataEmojiSection>\)/);
assert.match(catalog, /data class Unavailable\(val message: String, val onRetry: \(\(\) -> Unit\)\? = null\)/);
assert.match(catalog, /fun communityEmojiCatalogState\(/);
assert.match(catalog, /atlasCellCountResolver/);
assert.match(catalog, /CommunityEmojiCatalogState\.Unavailable\(labels\.empty, onRetry\)/);
assert.match(catalogTest, /catalog provider fails closed when atlas validation fails/);
assert.match(panel, /retryLabel: String = CommunityEmojiLabels\(\)\.retry/);
assert.match(panel, /onRetry: \(\(\) -> Unit\)\? = null/);
assert.match(panel, /contentDescription = errorMessage/);
assert.match(panel, /contentDescription = retryLabel/);
assert.match(panel, /communityEmojiPanelSelectedSection/);
assert.doesNotMatch(panel, /selectedSectionKey = selectedSection\.key/);
assert.match(panel, /val isSelected = section\.key == selectedSection\.key/);
assert.match(androidPanel, /empty = stringResource\(R\.string\.emoji_empty\)/);
assert.match(androidPanel, /emptyMessage = stringResource\(R\.string\.emoji_empty\)/);
assert.doesNotMatch(panel, /if \(sections\.isEmpty\(\)\) return/);
assert.doesNotMatch(panel, /val selectedSection = sections\.firstOrNull \{ it\.key == selectedSectionKey \} \?: return/);
assert.match(panel, /import androidx\.compose\.ui\.semantics\.contentDescription/);
assert.match(panel, /import androidx\.compose\.ui\.semantics\.selected/);
assert.match(panel, /import androidx\.compose\.ui\.semantics\.stateDescription/);
assert.match(panel, /communityEmojiSectionTestTag\(section\.key\)/);
assert.match(panel, /communityEmojiGridTestTag\(selectedSection\.key\)/);
assert.match(panel, /communityEmojiCellTestTag\(selectedSection\.key, index\)/);
assert.match(panel, /clickable\(role = Role\.Button\)/);
assert.match(panel, /selected = isSelected/);
assert.match(panel, /stateDescription = if \(isSelected\) "selected" else "not selected"/);
assert.match(panel, /contentDescription = communityEmojiSectionTestTag\(section\.key\)/);
assert.match(panel, /contentDescription = communityEmojiGridTestTag\(selectedSection\.key\)/);
assert.match(panel, /contentDescription = communityEmojiCellTestTag\(selectedSection\.key, index\)/);
assert.match(panel, /clickable\(role = Role\.Button\) \{ onEmojiClick\(emoji\) \}/);
assert.match(commentInput, /isSending: Boolean = false/);
assert.match(commentInput, /enabled = !isSending/);
assert.match(commentTextFieldExpect, /enabled: Boolean = true/);
assert.match(commentTextFieldAndroid, /enabled = enabled/);
assert.match(commentTextFieldIos, /enabled = enabled/);
assert.match(commentTextFieldWasm, /enabled = enabled/);
console.log('Community emoji atlas contract passed.');
