-- Read-only exhaustive catalogue audit for the base native-push package.
-- Emits schema metadata only; it never reads push rows, Vault, or invokes transport.
with observation as (
select jsonb_build_object(
  'extension',(select jsonb_agg(jsonb_build_object('name',e.extname,'schema',n.nspname,'version',e.extversion,'relocatable',e.extrelocatable) order by e.extname) from pg_extension e join pg_namespace n on n.oid=e.extnamespace where e.extname='pg_net'),
  'tables',(select jsonb_agg(jsonb_build_object('name',c.relname,'rls',c.relrowsecurity,'forceRls',c.relforcerowsecurity) order by c.relname) from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relname in ('push_tokens','push_delivery_log') and c.relkind='r'),
  'columns',(select jsonb_agg(jsonb_build_object('table',c.relname,'ordinal',a.attnum,'name',a.attname,'type',format_type(a.atttypid,a.atttypmod),'notNull',a.attnotnull,'default',pg_get_expr(d.adbin,d.adrelid),'identity',a.attidentity,'generated',a.attgenerated) order by c.relname,a.attnum) from pg_attribute a join pg_class c on c.oid=a.attrelid join pg_namespace n on n.oid=c.relnamespace left join pg_attrdef d on d.adrelid=a.attrelid and d.adnum=a.attnum where n.nspname='public' and ((c.relname='push_tokens' and a.attname in ('id','user_id','auth_user_id','token','platform','app_version','created_at','updated_at','last_seen_at')) or (c.relname='push_delivery_log' and a.attname in ('id','message_id','profile_id','push_token_id','status','error_text','created_at','sent_at'))) and not a.attisdropped),
  'constraints',(select jsonb_agg(jsonb_build_object('table',c.relname,'name',con.conname,'type',con.contype,'definition',pg_get_constraintdef(con.oid,true),'validated',con.convalidated) order by c.relname,con.conname) from pg_constraint con join pg_class c on c.oid=con.conrelid join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and ((c.relname='push_tokens' and con.conname in ('push_tokens_pkey','push_tokens_user_id_fkey','push_tokens_auth_user_id_fkey','push_tokens_token_key','push_tokens_platform_check')) or (c.relname='push_delivery_log' and con.conname in ('push_delivery_log_pkey','push_delivery_log_message_id_fkey','push_delivery_log_profile_id_fkey','push_delivery_log_push_token_id_fkey','push_delivery_log_status_check','push_delivery_log_message_profile_token_key')))),
  'indexes',(select jsonb_agg(jsonb_build_object('table',tc.relname,'name',ic.relname,'definition',pg_get_indexdef(i.indexrelid),'valid',i.indisvalid,'ready',i.indisready,'unique',i.indisunique,'primary',i.indisprimary) order by tc.relname,ic.relname) from pg_index i join pg_class ic on ic.oid=i.indexrelid join pg_class tc on tc.oid=i.indrelid join pg_namespace n on n.oid=tc.relnamespace where n.nspname='public' and ic.relname in ('push_tokens_pkey','push_tokens_token_key','push_tokens_user_idx','push_tokens_auth_user_idx','push_tokens_last_seen_idx','push_delivery_log_pkey','push_delivery_log_message_profile_token_key','push_delivery_log_message_idx','push_delivery_log_profile_idx')),
  'identitySequences',(select jsonb_agg(jsonb_build_object('table',tc.relname,'column',a.attname,'sequenceSchema',sn.nspname,'sequenceName',sc.relname,'dependencyType',dep.deptype::text,'type',format_type(s.seqtypid,null),'start',s.seqstart::text,'increment',s.seqincrement::text,'minimum',s.seqmin::text,'maximum',s.seqmax::text,'cache',s.seqcache::text,'cycle',s.seqcycle) order by tc.relname,a.attname) from pg_attribute a join pg_class tc on tc.oid=a.attrelid join pg_namespace tn on tn.oid=tc.relnamespace join pg_depend dep on dep.refclassid='pg_class'::regclass and dep.refobjid=tc.oid and dep.refobjsubid=a.attnum and dep.classid='pg_class'::regclass and dep.deptype='i' join pg_class sc on sc.oid=dep.objid and sc.relkind='S' join pg_namespace sn on sn.oid=sc.relnamespace join pg_sequence s on s.seqrelid=sc.oid where tn.nspname='public' and tc.relname='push_delivery_log' and a.attname='id' and a.attidentity='d'),
  'policies',(select jsonb_agg(jsonb_build_object('table',tablename,'name',policyname,'permissive',permissive,'roles',roles,'cmd',cmd,'qual',qual,'withCheck',with_check) order by tablename,policyname) from pg_policies where schemaname='public' and tablename='push_tokens' and policyname in ('push_tokens_select_own','push_tokens_delete_own')),
  'functions',(select jsonb_agg(jsonb_build_object('name',p.proname,'args',pg_get_function_identity_arguments(p.oid),'result',pg_get_function_result(p.oid),'language',l.lanname,'securityDefiner',p.prosecdef,'volatility',p.provolatile::text,'config',coalesce(p.proconfig,array[]::text[]),'md5',md5(pg_get_functiondef(p.oid)),'publicExecute',has_function_privilege('public',p.oid,'EXECUTE'),'anonExecute',has_function_privilege('anon',p.oid,'EXECUTE'),'authenticatedExecute',has_function_privilege('authenticated',p.oid,'EXECUTE'),'serviceRoleExecute',has_function_privilege('service_role',p.oid,'EXECUTE'),'acl',p.proacl) order by p.proname) from pg_proc p join pg_namespace n on n.oid=p.pronamespace join pg_language l on l.oid=p.prolang where n.nspname='public' and p.proname in ('quata_register_push_token','quata_enqueue_chat_push')),
  'triggers',(select jsonb_agg(jsonb_build_object('table',c.relname,'name',t.tgname,'definition',pg_get_triggerdef(t.oid,true),'enabled',t.tgenabled::text,'function',p.proname) order by c.relname,t.tgname) from pg_trigger t join pg_class c on c.oid=t.tgrelid join pg_namespace n on n.oid=c.relnamespace join pg_proc p on p.oid=t.tgfoid where n.nspname='public' and c.relname='chat_messages' and t.tgname='chat_messages_after_insert_push' and not t.tgisinternal)
) as metadata
)
select jsonb_build_object(
  'metadata',metadata,
  'digests',jsonb_build_object(
    'extensionMd5',md5((metadata->'extension')::text),'tablesMd5',md5((metadata->'tables')::text),'columnsMd5',md5((metadata->'columns')::text),'constraintsMd5',md5((metadata->'constraints')::text),'indexesMd5',md5((metadata->'indexes')::text),'identitySequencesMd5',md5((metadata->'identitySequences')::text),'policiesMd5',md5((metadata->'policies')::text),'functionsMd5',md5((metadata->'functions')::text),'triggersMd5',md5((metadata->'triggers')::text)
  ),
  'allEffectsExact',
    md5((metadata->'extension')::text) = '96addb61d73e984884cb0952cd804fd7'
    and md5((metadata->'tables')::text) = '9e17c8ed2398a88c02c1f45ed7cbe8f8'
    and md5((metadata->'columns')::text) = '72f61f126757151d6ed4ccd5e02e84ce'
    and md5((metadata->'constraints')::text) = '10933f4cbdae9b4a01f7457014c088e3'
    and md5((metadata->'indexes')::text) = 'daa4f8c89aea0b9d4ba5996b78a46dfe'
    and md5((metadata->'identitySequences')::text) = '1fbac4444d6729a2ce9eca59b7784d0f'
    and md5((metadata->'policies')::text) = '60b19956ccd226b4878c8db3d6af5d73'
    and md5((metadata->'functions')::text) = '0739ff80b769a862b588ff5cd33252f7'
    and md5((metadata->'triggers')::text) = 'f1720ed7e3290565412dc7152285bd49'
)
from observation;
