with observation as (
select jsonb_build_object(
  'extension',(select jsonb_agg(jsonb_build_object('name',e.extname,'schema',n.nspname,'version',e.extversion,'relocatable',e.extrelocatable) order by e.extname) from pg_extension e join pg_namespace n on n.oid=e.extnamespace where e.extname='pgcrypto'),
  'profileColumns',(select jsonb_agg(jsonb_build_object('ordinal',a.attnum,'name',a.attname,'type',format_type(a.atttypid,a.atttypmod),'notNull',a.attnotnull,'default',pg_get_expr(d.adbin,d.adrelid),'identity',a.attidentity,'generated',a.attgenerated) order by a.attnum) from pg_attribute a join pg_class c on c.oid=a.attrelid join pg_namespace n on n.oid=c.relnamespace left join pg_attrdef d on d.adrelid=a.attrelid and d.adnum=a.attnum where n.nspname='public' and c.relname='community_profiles' and a.attname in ('is_admin','is_official') and not a.attisdropped),
  'profileIndexes',(select jsonb_agg(jsonb_build_object('name',ic.relname,'definition',pg_get_indexdef(i.indexrelid),'valid',i.indisvalid,'ready',i.indisready,'unique',i.indisunique,'primary',i.indisprimary) order by ic.relname) from pg_index i join pg_class ic on ic.oid=i.indexrelid join pg_class tc on tc.oid=i.indrelid join pg_namespace n on n.oid=tc.relnamespace where n.nspname='public' and tc.relname='community_profiles' and ic.relname in ('community_profiles_is_admin_idx','community_profiles_is_official_idx')),
  'tables',(select jsonb_agg(jsonb_build_object('name',c.relname,'rls',c.relrowsecurity,'forceRls',c.relforcerowsecurity) order by c.relname) from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relname in ('official_posts','official_post_likes','official_post_comments') and c.relkind='r'),
  'columns',(select jsonb_agg(jsonb_build_object('table',c.relname,'ordinal',a.attnum,'name',a.attname,'type',format_type(a.atttypid,a.atttypmod),'notNull',a.attnotnull,'default',pg_get_expr(d.adbin,d.adrelid),'identity',a.attidentity,'generated',a.attgenerated) order by c.relname,a.attnum) from pg_attribute a join pg_class c on c.oid=a.attrelid join pg_namespace n on n.oid=c.relnamespace left join pg_attrdef d on d.adrelid=a.attrelid and d.adnum=a.attnum where n.nspname='public' and ((c.relname='official_posts' and a.attname in ('id','profile_id','title','summary','post_type','content_html','media_url','media_type','link_url','is_live','is_published','published_at','created_at','updated_at','deleted_at')) or (c.relname='official_post_likes' and a.attname in ('id','official_post_id','profile_id','created_at')) or (c.relname='official_post_comments' and a.attname in ('id','official_post_id','profile_id','body','created_at','updated_at','deleted_at'))) and not a.attisdropped),
  'constraints',(select jsonb_agg(jsonb_build_object('table',c.relname,'name',con.conname,'type',con.contype,'definition',pg_get_constraintdef(con.oid,true),'validated',con.convalidated) order by c.relname,con.conname) from pg_constraint con join pg_class c on c.oid=con.conrelid join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relname in ('official_posts','official_post_likes','official_post_comments') and con.conname in ('official_posts_pkey','official_posts_profile_id_fkey','official_posts_type_check','official_posts_media_type_check','official_posts_content_check','official_post_likes_pkey','official_post_likes_official_post_id_fkey','official_post_likes_profile_id_fkey','official_post_likes_unique','official_post_comments_pkey','official_post_comments_official_post_id_fkey','official_post_comments_profile_id_fkey','official_post_comments_body_check')),
  'indexes',(select jsonb_agg(jsonb_build_object('table',tc.relname,'name',ic.relname,'definition',pg_get_indexdef(i.indexrelid),'valid',i.indisvalid,'ready',i.indisready,'unique',i.indisunique,'primary',i.indisprimary) order by tc.relname,ic.relname) from pg_index i join pg_class ic on ic.oid=i.indexrelid join pg_class tc on tc.oid=i.indrelid join pg_namespace n on n.oid=tc.relnamespace where n.nspname='public' and ((tc.relname='official_posts' and ic.relname in ('official_posts_published_idx','official_posts_profile_idx')) or (tc.relname='official_post_likes' and ic.relname='official_post_likes_post_idx') or (tc.relname='official_post_comments' and ic.relname='official_post_comments_post_idx'))),
  'functions',(select jsonb_agg(jsonb_build_object('name',p.proname,'args',pg_get_function_identity_arguments(p.oid),'result',pg_get_function_result(p.oid),'language',l.lanname,'securityDefiner',p.prosecdef,'volatility',p.provolatile::text,'config',coalesce(p.proconfig,array[]::text[]),'md5',md5(replace(pg_get_functiondef(p.oid),E'\r\n',E'\n')),'acl',p.proacl) order by p.proname) from pg_proc p join pg_namespace n on n.oid=p.pronamespace join pg_language l on l.oid=p.prolang where n.nspname='public' and p.proname in ('quata_current_profile_id','quata_current_profile_is_admin','quata_current_role_is_service','quata_guard_profile_roles','quata_guard_official_posts','quata_guard_official_post_likes','quata_guard_official_post_comments')),
  'triggers',(select jsonb_agg(jsonb_build_object('table',c.relname,'name',t.tgname,'definition',pg_get_triggerdef(t.oid,true),'enabled',t.tgenabled::text,'function',p.proname) order by c.relname,t.tgname) from pg_trigger t join pg_class c on c.oid=t.tgrelid join pg_namespace n on n.oid=c.relnamespace join pg_proc p on p.oid=t.tgfoid where n.nspname='public' and t.tgname in ('quata_guard_profile_roles_trg','quata_guard_official_posts_trg','quata_guard_official_post_likes_trg','quata_guard_official_post_comments_trg') and not t.tgisinternal),
  'privileges',(select jsonb_agg(jsonb_build_object('table',table_name,'role',role_name,'select',has_table_privilege(role_name,format('public.%I',table_name),'SELECT'),'insert',has_table_privilege(role_name,format('public.%I',table_name),'INSERT'),'update',has_table_privilege(role_name,format('public.%I',table_name),'UPDATE'),'delete',has_table_privilege(role_name,format('public.%I',table_name),'DELETE'),'truncate',has_table_privilege(role_name,format('public.%I',table_name),'TRUNCATE'),'references',has_table_privilege(role_name,format('public.%I',table_name),'REFERENCES'),'trigger',has_table_privilege(role_name,format('public.%I',table_name),'TRIGGER'),'maintain',has_table_privilege(role_name,format('public.%I',table_name),'MAINTAIN')) order by table_name,role_name) from unnest(array['official_posts','official_post_likes','official_post_comments']) table_name cross join unnest(array['anon','authenticated']) role_name),
  'profileRoleColumnPrivileges',(select jsonb_agg(jsonb_build_object('column',a.attname,'acl',a.attacl,'directAnonUpdate',exists(select 1 from aclexplode(coalesce(a.attacl,'{}'::aclitem[])) x join pg_roles r on r.oid=x.grantee where r.rolname='anon' and x.privilege_type='UPDATE'),'directAuthenticatedUpdate',exists(select 1 from aclexplode(coalesce(a.attacl,'{}'::aclitem[])) x join pg_roles r on r.oid=x.grantee where r.rolname='authenticated' and x.privilege_type='UPDATE'),'effectiveAnonUpdate',has_column_privilege('anon',c.oid,a.attname,'UPDATE'),'effectiveAuthenticatedUpdate',has_column_privilege('authenticated',c.oid,a.attname,'UPDATE')) order by a.attname) from pg_attribute a join pg_class c on c.oid=a.attrelid join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relname='community_profiles' and a.attname in ('is_admin','is_official') and not a.attisdropped),
  'publication',(select jsonb_agg(jsonb_build_object('publication',p.pubname,'table',c.relname,'columns',(select jsonb_agg(a.attname order by k.ordinality) from unnest(pr.prattrs) with ordinality k(attnum,ordinality) join pg_attribute a on a.attrelid=c.oid and a.attnum=k.attnum),'rowFilter',pg_get_expr(pr.prqual,pr.prrelid,true)) order by c.relname) from pg_publication_rel pr join pg_publication p on p.oid=pr.prpubid join pg_class c on c.oid=pr.prrelid join pg_namespace n on n.oid=c.relnamespace where p.pubname='supabase_realtime' and n.nspname='public' and c.relname in ('official_posts','official_post_likes','official_post_comments')),
  'dataPostcondition',(select jsonb_build_object('adminCandidateCount',(select count(*) from public.community_profiles where id in ('757edf3f-8b7f-40cf-b775-cd3ef3b07f4c'::uuid,'f99a8051-4ef8-4b93-984c-7a011937919f'::uuid) or lower(coalesce(display_name,nombre,'')) in ('gabriel','juan') or regexp_replace(coalesce(phone_e164,phone,telefono,concat(coalesce(country_code,''),coalesce(phone_local,'')),''),'\D','','g') in ('34680242606','240555352016')),'allAdminCandidatesSatisfied',not exists(select 1 from public.community_profiles where (id in ('757edf3f-8b7f-40cf-b775-cd3ef3b07f4c'::uuid,'f99a8051-4ef8-4b93-984c-7a011937919f'::uuid) or lower(coalesce(display_name,nombre,'')) in ('gabriel','juan') or regexp_replace(coalesce(phone_e164,phone,telefono,concat(coalesce(country_code,''),coalesce(phone_local,'')),''),'\D','','g') in ('34680242606','240555352016')) and not is_admin),'officialCandidateCount',(select count(*) from public.community_profiles where id='757edf3f-8b7f-40cf-b775-cd3ef3b07f4c'::uuid or lower(coalesce(display_name,nombre,''))='gabriel' or regexp_replace(coalesce(phone_e164,phone,telefono,concat(coalesce(country_code,''),coalesce(phone_local,'')),''),'\D','','g')='34680242606'),'allOfficialCandidatesSatisfied',not exists(select 1 from public.community_profiles where (id='757edf3f-8b7f-40cf-b775-cd3ef3b07f4c'::uuid or lower(coalesce(display_name,nombre,''))='gabriel' or regexp_replace(coalesce(phone_e164,phone,telefono,concat(coalesce(country_code,''),coalesce(phone_local,'')),''),'\D','','g')='34680242606') and not is_official)))
) metadata
)
select jsonb_build_object('metadata',metadata,'digests',jsonb_build_object(
  'extensionMd5',md5((metadata->'extension')::text),'profileColumnsMd5',md5((metadata->'profileColumns')::text),'profileIndexesMd5',md5((metadata->'profileIndexes')::text),'tablesMd5',md5((metadata->'tables')::text),'columnsMd5',md5((metadata->'columns')::text),'constraintsMd5',md5((metadata->'constraints')::text),'indexesMd5',md5((metadata->'indexes')::text),'functionsMd5',md5((metadata->'functions')::text),'triggersMd5',md5((metadata->'triggers')::text),'privilegesMd5',md5((metadata->'privileges')::text),'profileRoleColumnPrivilegesMd5',md5((metadata->'profileRoleColumnPrivileges')::text),'publicationMd5',md5((metadata->'publication')::text),'dataPostconditionMd5',md5((metadata->'dataPostcondition')::text)),
  'allEffectsExact',
    md5((metadata->'extension')::text)='04b815c392d8e44b2a1d82787b5ad06a'
    and md5((metadata->'profileColumns')::text)='084400c6e76e03ac81c02c39961f5b45'
    and md5((metadata->'profileIndexes')::text)='8260abce5621506784f3a8f2e108d853'
    and md5((metadata->'tables')::text)='f43f74ddf31a716e78fead128d8b20ab'
    and md5((metadata->'columns')::text)='d106ad79e741d72d24b8813f433c9bd4'
    and md5((metadata->'constraints')::text)='13d74a98903ad3dbb8f4ec0d5d6b677f'
    and md5((metadata->'indexes')::text)='0fb1fa28a0ee4e4764f11479a025a2d9'
    and md5((metadata->'functions')::text)='5c5718f1a5dd7a3d73345cae94a77d4d'
    and md5((metadata->'triggers')::text)='11d1d0adf88f7621326d7748335a7d06'
    and md5((metadata->'privileges')::text)='2c89014c4f432e1f7fa67a554957c473'
    and md5((metadata->'profileRoleColumnPrivileges')::text)='c38db2590bf4a6853e3549d3ba367c15'
    and md5((metadata->'publication')::text)='96caccf260f5d892a98ef7b937555cfa'
    and (metadata->'dataPostcondition'->>'allAdminCandidatesSatisfied')::boolean
    and (metadata->'dataPostcondition'->>'allOfficialCandidatesSatisfied')::boolean
) from observation;
