import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";

const root = new URL("../", import.meta.url);
const source = (path) => readFileSync(new URL(path, root), "utf8");

test("shared action rail exposes stable comments anchors for Feed and Official", () => {
  const rail = source("designsystem/src/commonMain/kotlin/com/quata/core/ui/components/QuataFeedActionRail.kt");
  const compactControls = source("designsystem/src/commonMain/kotlin/com/quata/core/ui/components/CompactControls.kt");
  const feed = source("feature/feed/src/commonMain/kotlin/com/quata/feature/feed/presentation/FeedReelPostContent.kt");
  const official = source("feature/official/src/commonMain/kotlin/com/quata/feature/official/presentation/OfficialPostActionRailContent.kt");
  assert.match(rail, /actionTestTagPrefix/);
  assert.match(rail, /actionTestTagSuffix/);
  assert.match(rail, /quataFeedActionTestTag\(actionTestTagPrefix, "comments", actionTestTagSuffix\)/);
  assert.match(rail, /accessibleDescription = listOfNotNull\(description, testTag\)\.joinToString\(" "\)/);
  assert.match(rail, /contentDescription = accessibleDescription/);
  assert.match(compactControls, /contentDescription: String\? = null/);
  assert.match(compactControls, /accessibleDescription = listOfNotNull\(contentDescription, testTag\)\.joinToString\(" "\)/);
  assert.match(feed, /actionTestTagPrefix = "feed\.action"/);
  assert.match(feed, /actionTestTagSuffix = post\.id/);
  assert.match(official, /actionTestTagPrefix = "official\.action"/);
  assert.match(official, /actionTestTagSuffix = post\.id/);
});

test("Feed and Official comments use the common emoji picker and common comment input tags", () => {
  const floatingPanel = source("designsystem/src/commonMain/kotlin/com/quata/core/ui/components/QuataFloatingPanelContent.kt");
  const portraitPanel = source("designsystem/src/commonMain/kotlin/com/quata/core/ui/components/QuataCommentsPanelPortraitContent.kt");
  const landscapePanel = source("designsystem/src/commonMain/kotlin/com/quata/core/ui/components/QuataCommentsPanelLandscapeContent.kt");
  const panelError = source("designsystem/src/commonMain/kotlin/com/quata/core/ui/components/QuataCommentsPanelErrorContent.kt");
  const feed = source("feature/feed/src/commonMain/kotlin/com/quata/feature/feed/presentation/FeedScreenHost.kt");
  const feedEvents = source("feature/feed/src/commonMain/kotlin/com/quata/feature/feed/presentation/FeedUiEvent.kt");
  const feedViewModel = source("feature/feed/src/commonMain/kotlin/com/quata/feature/feed/presentation/FeedViewModel.kt");
  const feedOptimisticTest = source("feature/feed/src/commonTest/kotlin/com/quata/feature/feed/presentation/FeedOptimisticCommentsTest.kt");
  const official = source("feature/official/src/commonMain/kotlin/com/quata/feature/official/presentation/OfficialCommentsPanelContent.kt");
  const officialHost = source("feature/official/src/commonMain/kotlin/com/quata/feature/official/presentation/OfficialFeedScreenHost.kt");
  const officialViewModel = source("feature/official/src/commonMain/kotlin/com/quata/feature/official/presentation/OfficialFeedViewModel.kt");
  const officialOptimisticTest = source("feature/official/src/commonTest/kotlin/com/quata/feature/official/presentation/OfficialOptimisticCommentsTest.kt");
  for (const [label, content, prefix] of [["feed", feed, "feed"], ["official", official, "official"]]) {
    assert.match(content, /CommunityEmojiPanelContent/, `${label}:picker`);
    assert.match(content, /insertAtSelection/, `${label}:insert`);
    assert.match(content, new RegExp(`${prefix}\\.comments\\.emoji`), `${label}:emoji_tag`);
    assert.match(content, /contentDescription = strings\.showEmojis/, `${label}:emoji_accessible_tag`);
    assert.match(content, new RegExp(`${prefix}\\.comments\\.input`), `${label}:input_tag`);
    assert.match(content, new RegExp(`${prefix}\\.comments\\.send`), `${label}:send_tag`);
    assert.match(content, /emptyMessage = strings\.emojiLabels\.empty/, `${label}:empty_localized`);
  }
  assert.match(feedEvents, /data class FocusPost/);
  assert.match(feed, /FeedUiEvent\.FocusPost\(activeFocusedPostId\)/);
  assert.match(feedViewModel, /repository\.refreshPost\(postId\)/);
  assert.match(feedViewModel, /feedStore\.prependIfMissing\(post\)/);
  assert.match(feedViewModel, /feedStore\.replace\(postId\) \{ it\.withoutLocalPendingComment\(comment\) \}/);
  assert.match(feedViewModel, /withoutLocalPendingComment/);
  assert.match(feedOptimisticTest, /removesLocalPendingCommentWhenBackendMutationFails/);
  assert.match(feedOptimisticTest, /view model rolls back forced emoji comment failure and surfaces error/);
  assert.match(feedOptimisticTest, /FeedUiEvent\.AddComment/);
  assert.match(feedOptimisticTest, /😀 rollback/);
  assert.match(officialHost, /empty="No emojis available\."/);
  assert.match(officialHost, /empty="Aucun emoji disponible\."/);
  assert.match(officialViewModel, /feedStore\.replace\(postId\) \{ it\.withoutLocalPendingComment\(comment\) \}/);
  assert.match(officialViewModel, /exactLoadedPosts = exactLoadedPosts\.mapValues/);
  assert.match(officialOptimisticTest, /removesLocalPendingCommentAndCountWhenBackendMutationFails/);
  assert.match(officialOptimisticTest, /view model rolls back forced emoji comment failure and surfaces error/);
  assert.match(officialOptimisticTest, /OfficialFeedUiEvent\.AddComment/);
  assert.match(officialOptimisticTest, /😀 rollback/);
  assert.match(panelError, /QuataCommentsPanelErrorTestTag/);
  assert.match(panelError, /contentDescription = message/);
  assert.match(portraitPanel, /errorMessage: String\? = null/);
  assert.match(portraitPanel, /QuataCommentsPanelErrorContent/);
  assert.match(landscapePanel, /errorMessage: String\? = null/);
  assert.match(landscapePanel, /QuataCommentsPanelErrorContent/);
  assert.match(feed, /commentErrorMessage = state\.commentErrorsByPostId\[post\.id\]/);
  assert.match(feed, /commentErrorsByCommentId = state\.commentErrorsByCommentId/);
  assert.doesNotMatch(feed, /commentErrorMessage = state\.error/);
  assert.match(feed, /pendingCommentErrorMessage = pendingCommentId\?\.let\(commentErrorsByCommentId::get\)/);
  assert.match(feed, /visibleCommentErrorMessage = if \(pendingCommentId != null\) pendingCommentErrorMessage else commentErrorMessage/);
  assert.match(feed, /errorMessage = visibleCommentErrorMessage/);
  assert.match(feed, /errorTestTag = "feed\.comments\.error"/);
  assert.match(officialHost, /commentErrorMessage = state\.commentErrorsByPostId\[post\.id\]/);
  assert.match(officialHost, /commentErrorsByCommentId = state\.commentErrorsByCommentId/);
  assert.doesNotMatch(officialHost, /commentErrorMessage = state\.error/);
  assert.match(official, /pendingCommentErrorMessage = pendingCommentId\?\.let\(commentErrorsByCommentId::get\)/);
  assert.match(official, /visibleCommentErrorMessage = if \(pendingCommentId != null\) pendingCommentErrorMessage else commentErrorMessage/);
  assert.match(official, /errorMessage = visibleCommentErrorMessage/);
  assert.match(official, /errorTestTag = "official\.comments\.error"/);
  assert.match(feed, /pendingDraft = draft/);
  assert.match(feed, /pendingCommentId = comment\.id/);
  assert.match(feed, /confirmedCommentIds = state\.confirmedCommentIds/);
  assert.match(feed, /onConfirmedCommentConsumed = \{ viewModel\.onEvent\(FeedUiEvent\.ConfirmedCommentConsumed\(it\)\) \}/);
  assert.match(feed, /pendingId in confirmedCommentIds/);
  assert.match(feed, /if \(confirmed\) onConfirmedCommentConsumed\(pendingId\)/);
  assert.match(feedViewModel, /rollbackLocalPendingCommentFailure\(postId, comment, message\)/);
  assert.match(feedViewModel, /_uiState\.update \{ state -> state\.copy\([\s\S]*confirmedCommentIds = \(state\.confirmedCommentIds \+ comment\.id\)\.toList\(\)\.takeLast\(4\)\.toSet\(\)/);
  assert.match(feedViewModel, /_uiState\.update \{ state -> state\.copy\([\s\S]*commentErrorsByCommentId = \(state\.commentErrorsByCommentId \+ \(comment\.id to message\)\)\.takeLastEntries\(4\)/);
  assert.doesNotMatch(feedViewModel, /_uiState\.value = _uiState\.value\.copy/);
  assert.doesNotMatch(feedViewModel, /withLocalPendingCommentsFrom\(_uiState\.value\.posts/);
  assert.doesNotMatch(feedViewModel, /_uiState\.value\.posts\.associateBy/);
  assert.doesNotMatch(feedViewModel, /feedStore\.(setRealtime|replaceInitialPage|appendOlder)\(posts\.withLocalPendingComments/);
  assert.doesNotMatch(feedViewModel, /posts = feedStore\./);
  assert.match(feedViewModel, /posts = mergedPosts\.withLocalPendingCommentsFrom\(state\.posts\)/);
  assert.match(feedViewModel, /posts = feedPosts\.withLocalPendingCommentsFrom\(state\.posts\)/);
  assert.doesNotMatch(feedViewModel, /val posts = transformed\.takeIf[\s\S]*\?: _uiState\.value\.posts/);
  assert.match(feedOptimisticTest, /backend returns post retaining local id/);
  assert.match(feedOptimisticTest, /correlates forced comment failure by comment id/);
  assert.match(feedViewModel, /state\.posts\.replacePostIfPresent\(reconciled\)/);
  assert.match(feedViewModel, /posts = \(state\.posts\.takeIf \{ posts -> posts\.any \{ it\.id == postId \} \} \?: transformed\)\.map[\s\S]*commentErrorsByPostId = state\.commentErrorsByPostId \+ \(postId to message\)/);
  assert.doesNotMatch(feedViewModel, /confirmedCommentIds = \(_uiState\.value\.confirmedCommentIds \+ comment\.id\)/);
  assert.doesNotMatch(feedViewModel, /commentErrorsByCommentId = \(_uiState\.value\.commentErrorsByCommentId \+ \(comment\.id to message\)\)/);
  assert.doesNotMatch(feedViewModel, /removeLocalPendingComment\(postId, comment\)\s*_uiState\.value = _uiState\.value\.copy\(\s*commentErrorsByPostId/);
  assert.match(feed, /enabled = pendingCommentId == null/);
  assert.match(feed, /isSending = pendingCommentId != null/);
  assert.match(feed, /retryLabel = strings\.retry/);
  assert.match(feed, /communityEmojiCatalog: \(CommunityEmojiLabels, \(\(\) -> Unit\)\?\) -> CommunityEmojiCatalogState/);
  assert.match(feed, /emojiCatalogRetryToken \+= 1/);
  assert.match(feed, /CommunityEmojiCatalogState\.Unavailable/);
  assert.match(feed, /onRetry = catalogState\.onRetry/);
  assert.doesNotMatch(feed, /onRetry = \{ setEmojiPickerVisible\(false\); setEmojiPickerVisible\(true\) \}/);
  assert.match(official, /pendingDraft = draft/);
  assert.match(official, /pendingCommentId = comment\.id/);
  assert.match(officialHost, /confirmedCommentIds = state\.confirmedCommentIds/);
  assert.match(officialHost, /onConfirmedCommentConsumed = \{ viewModel\.onEvent\(OfficialFeedUiEvent\.ConfirmedCommentConsumed\(it\)\) \}/);
  assert.match(official, /pendingId in confirmedCommentIds/);
  assert.match(official, /if \(confirmed\) onConfirmedCommentConsumed\(pendingId\)/);
  assert.match(officialViewModel, /rollbackLocalPendingCommentFailure\(postId, comment, message\)/);
  assert.match(officialViewModel, /_uiState\.update \{ state -> state\.copy\([\s\S]*confirmedCommentIds = \(state\.confirmedCommentIds \+ comment\.id\)\.toList\(\)\.takeLast\(4\)\.toSet\(\)/);
  assert.match(officialViewModel, /_uiState\.update \{ state -> state\.copy\([\s\S]*commentErrorsByCommentId = \(state\.commentErrorsByCommentId \+ \(comment\.id to message\)\)\.takeLastEntries\(4\)/);
  assert.doesNotMatch(officialViewModel, /_uiState\.value = _uiState\.value\.copy/);
  assert.doesNotMatch(officialViewModel, /withLocalPendingCommentsFrom\(_uiState\.value\.posts/);
  assert.doesNotMatch(officialViewModel, /_uiState\.value\.posts\.associateBy/);
  assert.doesNotMatch(officialViewModel, /feedStore\.(setRealtime|replaceInitialPage|appendOlder)\(posts(?:\.withExactLoadedPosts\(\))?\.withLocalPendingComments/);
  assert.doesNotMatch(officialViewModel, /posts = feedStore\./);
  assert.match(officialViewModel, /posts = mergedPosts\.withLocalPendingCommentsFrom\(state\.posts\)/);
  assert.match(officialViewModel, /posts = feedPosts\.withLocalPendingCommentsFrom\(state\.posts\)/);
  assert.doesNotMatch(officialViewModel, /val posts = transformed\.takeIf[\s\S]*\?: _uiState\.value\.posts/);
  assert.match(officialOptimisticTest, /backend returns post retaining local id/);
  assert.match(officialOptimisticTest, /correlates forced comment failure by comment id/);
  assert.match(officialViewModel, /state\.posts\.replacePostIfPresent\(reconciled\)/);
  assert.match(officialViewModel, /posts = \(state\.posts\.takeIf \{ posts -> posts\.any \{ it\.id == postId \} \} \?: transformed\)\.map[\s\S]*commentErrorsByPostId = state\.commentErrorsByPostId \+ \(postId to message\)/);
  assert.doesNotMatch(officialViewModel, /confirmedCommentIds = \(_uiState\.value\.confirmedCommentIds \+ comment\.id\)/);
  assert.doesNotMatch(officialViewModel, /commentErrorsByCommentId = \(_uiState\.value\.commentErrorsByCommentId \+ \(comment\.id to message\)\)/);
  assert.doesNotMatch(officialViewModel, /removeLocalPendingComment\(postId, comment\)\s*_uiState\.value = _uiState\.value\.copy\(\s*commentErrorsByPostId/);
  assert.match(official, /enabled = pendingCommentId == null/);
  assert.match(official, /isSending = pendingCommentId != null/);
  assert.match(official, /retryLabel = strings\.retry/);
  assert.match(official, /emojiCatalogState: @Composable \(\(\) -> CommunityEmojiCatalogState\)\? = null/);
  assert.match(official, /emojiCatalogRetryToken \+= 1/);
  assert.match(official, /CommunityEmojiCatalogState\.Unavailable/);
  assert.match(official, /onRetry = catalogState\.onRetry/);
  assert.doesNotMatch(official, /onRetry = \{ setEmojiPickerVisible\(false\); setEmojiPickerVisible\(true\) \}/);
  assert.match(feed, /commentsPostId = null[\s\S]*onOpenUserProfile\(profileId\)/);
  assert.match(officialHost, /commentsPost = null[\s\S]*onOpenUserProfile\(profileId\)/);
  assert.match(floatingPanel, /windowInsetsBottomHeight\(WindowInsets\.ime\)\.background\(template\.colors\.surfaceRaised\)/);
  assert.match(floatingPanel, /navigationBarsPadding\(\)\.imePadding\(\)/);
});

test("shared Feed/Official comments fixtures centralize SQL, cleanup and polling", () => {
  const fixtures = source("scripts/e2e-fixtures/chat-attachments.mjs");
  assert.match(fixtures, /export async function seedFeedOfficialCommentsFixture/);
  assert.match(fixtures, /export async function cleanupFeedOfficialCommentsFixture/);
  assert.match(fixtures, /export async function pollFeedOfficialComment/);
  assert.match(fixtures, /export async function assertFeedOfficialCommentAbsent/);
  assert.match(fixtures, /insert into public\.community_posts/);
  assert.match(fixtures, /insert into public\.official_posts/);
  assert.match(fixtures, /cleanup_verified_feed_official_comments_residue_absent/);
});

test("Web runner records a real Feed and Official emoji-comment flow", () => {
  const runner = source("scripts/chat-actions-notifications-web-evidence.mjs");
  assert.match(runner, /--feed-official-comments-only/);
  assert.match(runner, /--feed-official-comments-error-only/);
  assert.match(runner, /options\.feedOfficialCommentsOnly/);
  assert.match(runner, /options\.feedOfficialCommentsErrorOnly/);
  assert.match(runner, /seedFeedOfficialCommentsFixture/);
  assert.match(runner, /assertFeedOfficialCommentAbsent/);
  assert.match(runner, /`feed\.action\.comments\.\$\{fixture\.feed\.postId\}`/);
  assert.match(runner, /`official\.action\.comments\.\$\{fixture\.official\.postId\}`/);
  assert.match(runner, /feed\.comments\.author\.\$\{fixture\.actorSession\.profileId\}/);
  assert.match(runner, /official\.comments\.author\.\$\{fixture\.actorSession\.profileId\}/);
  assert.match(runner, /assertCommentAuthorAnchorVisible/);
  assert.match(runner, /comment_author_profile_anchor_visible/);
  assert.doesNotMatch(runner, /comment_author_profile_opened/);
  assert.doesNotMatch(runner, /commentAuthorProfileBridgeFallbacks/);
  assert.doesNotMatch(runner, /bottom-sheet dismiss layer intercepted/);
  assert.match(runner, /visibleAriaLocator\(page, \[new RegExp\(escapeRegExp\(`\$\{prefix\}\.emoji`\)\)\]/);
  assert.match(runner, /visibleNativeControl\(page, \[new RegExp\(escapeRegExp\(`\$\{prefix\}\.emoji`\)\)\]/);
  assert.match(runner, /verifyCommunityEmojiPanelSections/);
  assert.match(runner, /communityEmojiPanelProbeSections/);
  assert.match(runner, /clickCommunityEmojiSection/);
  assert.match(runner, /emoji_frequent_cell_anchor_missing:community\.emoji\.cell\.frequent\.0/);
  assert.match(runner, /await attachScreenshot\(page, evidenceDir, `\$\{screenshotPrefix\}-\$\{section\}`\)/);
  assert.doesNotMatch(runner, /semantic_cell_was_observed_earlier_but_not_resolved_after_horizontal_scroll/);
  assert.doesNotMatch(runner, /communityEmojiPanelResetFallbacks/);
  assert.doesNotMatch(runner, /observedFrequentCellBounds/);
  assert.match(runner, /community\.emoji\.section\.\$\{section\}/);
  assert.match(runner, /community\.emoji\.grid\.\$\{section\}/);
  assert.match(runner, /community\.emoji\.cell\.\$\{section\}\.0/);
  assert.match(runner, /nativeControlsOnly/);
  assert.doesNotMatch(runner, /visibleAriaLocator\(page, \[\/Comentarios\|Comments\|Commentaires\/i\]/);
  assert.match(runner, /prefix: "feed\.comments"/);
  assert.match(runner, /prefix: "official\.comments"/);
  assert.match(runner, /feed_comments_emoji_created_from_ui_and_verified_by_db/);
  assert.match(runner, /official_comments_emoji_created_from_ui_and_verified_by_db/);
  assert.match(runner, /sendReplyFromCommentTag/);
  assert.match(runner, /clickNativeControlCenter\(page, nativeReplyButton/);
  assert.match(runner, /waitVisibleSeededSurfaceText\(page, `\$\{fixture\.marker\} feed post body`, "feed_official_comments_feed_post_marker_missing"\)/);
  assert.match(runner, /waitVisibleSeededSurfaceText\(page, fixture\.marker, "feed_official_comments_official_post_marker_missing"\)/);
  assert.match(runner, /pollFeedOfficialReplyComment/);
  assert.match(runner, /feed_comments_reply_created_from_ui_and_verified_by_db/);
  assert.match(runner, /official_comments_reply_created_from_ui_and_verified_by_db/);
  assert.match(runner, /cleanup_verified_feed_official_comments_residue_absent/);
  assert.match(runner, /feed_comments_forced_error_visible_and_rollback_verified/);
  assert.match(runner, /official_comments_forced_error_visible_and_rollback_verified/);
  assert.match(runner, /feed_official_comments_e2e_forced_feed_comment_failure/);
  assert.match(runner, /feed_official_comments_e2e_forced_official_comment_failure/);
  assert.match(runner, /feed_and_official_comment_error_rollback_verified_with_common_tags/);
  assert.match(runner, /quata\.feedOfficialComments\.forceFailure/);
  assert.match(runner, /isNonBlockingFeedOfficialSupabaseConflictFault/);
  assert.match(runner, /startsWith\("feed_official_comments_"\)/);
  assert.match(runner, /status of 409/i);
});

test("Android runner records the same Feed and Official emoji-comment flow", () => {
  const runner = source("scripts/chat-actions-notifications-android-evidence.mjs");
  const uiTest = source("app/src/androidTest/java/com/quata/feature/chat/presentation/chat/ChatActionsNotificationsInstrumentedTest.kt");
  assert.match(runner, /--feed-official-comments-only/);
  assert.match(runner, /--feed-official-comments-error-only/);
  assert.match(runner, /seedFeedOfficialCommentsFixture/);
  assert.match(runner, /assertFeedOfficialCommentAbsent/);
  assert.match(runner, /pollFeedOfficialComment/);
  assert.match(runner, /pollFeedOfficialReplyComment/);
  assert.match(runner, /quataChatActionsFeedCommentId/);
  assert.match(runner, /quataChatActionsOfficialReplyComment/);
  assert.match(runner, /quataChatActionsActorProfileId/);
  assert.match(runner, /cleanup_verified_feed_official_comments_residue_absent/);
  assert.match(runner, /feed_comments_forced_error_visible_and_rollback_verified/);
  assert.match(runner, /official_comments_forced_error_visible_and_rollback_verified/);
  assert.match(runner, /android-feed-comments-error-before\.png/);
  assert.match(runner, /android-feed-comments-error-after\.png/);
  assert.match(runner, /android-official-comments-error-before\.png/);
  assert.match(runner, /android-official-comments-error-after\.png/);
  assert.match(uiTest, /"feed-official-comments"/);
  assert.match(uiTest, /"feed-official-comments-error"/);
  assert.match(uiTest, /private val device: UiDevice by lazy \{ connectUiDevice\(\) \}/);
  assert.match(uiTest, /private fun connectUiDevice\(\): UiDevice/);
  assert.match(uiTest, /feed\.action\.comments\.\$feedPostId/);
  assert.match(uiTest, /official\.action\.comments\.\$officialPostId/);
  assert.match(uiTest, /feed\.comments\.author\.\$actorProfileId/);
  assert.match(uiTest, /official\.comments\.author\.\$actorProfileId/);
  assert.match(uiTest, /openProfileFromAuthorTag/);
  assert.doesNotMatch(uiTest, /requireReturnTag = false/);
  assert.match(uiTest, /requireReturnTag: Boolean = true/);
  assert.match(uiTest, /feed\.comments\.emoji/);
  assert.match(uiTest, /official\.comments\.emoji/);
  assert.match(uiTest, /verifyCommunityEmojiPanelSections/);
  assert.match(uiTest, /communityEmojiPanelProbeSections/);
  assert.match(uiTest, /community\.emoji\.sections/);
  assert.match(uiTest, /community\.emoji\.grid\.\$section/);
  assert.match(uiTest, /community\.emoji\.cell\.frequent\.0/);
  assert.match(uiTest, /waitForTag\("community\.emoji\.panel", "comments emoji panel", 10_000\)[\s\S]*clickStableTag\("community\.emoji\.cell\.frequent\.0"\)/);
  assert.match(uiTest, /sendReplyCommentFromOpenPanel/);
  assert.match(uiTest, /sendFailingEmojiCommentFromOpenPost/);
  assert.match(uiTest, /quata_feed_official_comments_evidence/);
  assert.match(uiTest, /\$prefix\.reply\.\$replyToCommentId/);
  assert.match(uiTest, /compose\.onNodeWithTag\(replyTag, useUnmergedTree = true\)\.performClick\(\)/);
});

test("Android evidence runner serializes instrumented runs sharing com.quata.test", () => {
  const runner = source("scripts/chat-actions-notifications-android-evidence.mjs");
  assert.match(runner, /androidEvidenceLockPath/);
  assert.match(runner, /\.chat-actions-notifications\.lock/);
  assert.match(runner, /acquireAndroidEvidenceLock/);
  assert.match(runner, /android_evidence_lock_timeout/);
  assert.match(runner, /releaseAndroidEvidenceLock/);
});

test("iOS runner records the same Feed and Official emoji-comment flow", () => {
  const runner = source("scripts/chat-actions-notifications-ios-evidence.mjs");
  const wrapper = source("scripts/run-ios-chat-actions-notifications-ui-test.sh");
  const uiTest = source("iosApp/iosAppUITests/QuataIosAuthenticatedChatActionsNotificationsUITests.swift");
  assert.match(runner, /--feed-official-comments-only/);
  assert.match(runner, /--feed-official-comments-error-only/);
  assert.match(runner, /QUATA_IOS_CHAT_FEED_OFFICIAL_COMMENTS_UI_E2E/);
  assert.match(runner, /QUATA_IOS_CHAT_FEED_OFFICIAL_COMMENTS_ERROR_UI_E2E/);
  assert.match(runner, /QUATA_IOS_CHAT_ACTOR_PROFILE_ID/);
  assert.match(runner, /seedFeedOfficialCommentsFixture/);
  assert.match(runner, /assertFeedOfficialCommentAbsent/);
  assert.match(runner, /pollFeedOfficialComment/);
  assert.match(runner, /pollFeedOfficialReplyComment/);
  assert.match(runner, /QUATA_IOS_CHAT_FEED_COMMENTS_COMMENT_ID/);
  assert.match(runner, /QUATA_IOS_CHAT_OFFICIAL_COMMENTS_REPLY_COMMENT/);
  assert.match(runner, /cleanup_verified_feed_official_comments_residue_absent/);
  assert.match(runner, /feed_comments_forced_error_visible_and_rollback_verified/);
  assert.match(runner, /official_comments_forced_error_visible_and_rollback_verified/);
  assert.match(runner, /testFeedAndOfficialCommentsForcedErrorRollsBackSharedEmojiComment/);
  assert.match(wrapper, /testFeedAndOfficialCommentsUseSharedEmojiPicker/);
  assert.match(wrapper, /testFeedAndOfficialCommentsForcedErrorRollsBackSharedEmojiComment/);
  assert.match(wrapper, /QUATA_IOS_CHAT_FEED_COMMENTS_POST_ID/);
  assert.match(wrapper, /QUATA_IOS_CHAT_FEED_COMMENTS_COMMENT_ID/);
  assert.match(wrapper, /QUATA_IOS_CHAT_FEED_COMMENTS_REPLY_COMMENT/);
  assert.match(wrapper, /QUATA_IOS_CHAT_OFFICIAL_COMMENTS_POST_ID/);
  assert.match(wrapper, /QUATA_IOS_CHAT_OFFICIAL_COMMENTS_COMMENT_ID/);
  assert.match(wrapper, /QUATA_IOS_CHAT_OFFICIAL_COMMENTS_REPLY_COMMENT/);
  assert.match(wrapper, /\|\| "\$QUATA_IOS_CHAT_FEED_OFFICIAL_COMMENTS_ERROR_UI_E2E" == "1"/);
  assert.match(wrapper, /&& "\$QUATA_IOS_CHAT_FEED_OFFICIAL_COMMENTS_ERROR_UI_E2E" != "1"/);
  assert.match(wrapper, /run_and_require "\$feed_official_comments_error" "\$feed_official_comments_error_method" "\$QUATA_IOS_CHAT_ACTIONS_NOTIFICATIONS_LOG_DIR\/feed-official-comments-error\.log" 720/);
  assert.match(wrapper, /run_and_require "\$feed_official_comments" "\$feed_official_comments_method" "\$QUATA_IOS_CHAT_ACTIONS_NOTIFICATIONS_LOG_DIR\/feed-official-comments\.log" 840/);
  assert.match(wrapper, /stale_xctest_bundle/);
  assert.match(wrapper, /-newer "\$xctestrun"/);
  assert.match(runner, /assertIosFeedOfficialEmojiPanelEvidence\(options\)/);
  assert.match(runner, /ios_feed_official_emoji_panel_evidence_missing/);
  assert.match(runner, /ios-\$\{surface\}-comments-emoji-before-panel-\$\{section\}/);
  assert.match(uiTest, /func testFeedAndOfficialCommentsUseSharedEmojiPicker/);
  assert.match(uiTest, /func testFeedAndOfficialCommentsForcedErrorRollsBackSharedEmojiComment/);
  assert.match(uiTest, /QUATA_IOS_FEED_OFFICIAL_COMMENTS_FORCE_FAILURE/);
  assert.ok(uiTest.includes('feed.action.comments.\\(feedPostId)'));
  assert.ok(uiTest.includes('official.action.comments.\\(officialPostId)'));
  assert.ok(uiTest.includes('feed.comments.author.\\(actorProfileId)'));
  assert.ok(uiTest.includes('official.comments.author.\\(actorProfileId)'));
  assert.match(uiTest, /must expose a stable comment author profile anchor/);
  assert.match(uiTest, /feed\.comments\.emoji/);
  assert.match(uiTest, /official\.comments\.emoji/);
  assert.match(uiTest, /verifyCommunityEmojiPanelSections/);
  assert.match(uiTest, /verifyCommunityEmojiFrequentSection/);
  assert.doesNotMatch(uiTest, /verifyFullEmojiCatalog: false/);
  assert.match(uiTest, /communityEmojiPanelProbeSections/);
  assert.match(uiTest, /communityEmojiPanelIosEvidenceSections/);
  assert.match(uiTest, /community\.emoji\.sections/);
  assert.match(uiTest, /community\.emoji\.grid\.\\\(section\)/);
  assert.match(uiTest, /community\.emoji\.cell\.frequent\.0/);
  assert.match(uiTest, /sendReplyCommentFromTaggedSurface/);
  assert.match(uiTest, /sendFailingEmojiCommentFromTaggedSurface/);
  assert.ok(uiTest.includes('feed.comments.reply.\\(feedCommentId)'));
});

test("Feed and Official selector empty and error states are evidenced through the shared emoji panel", () => {
  const catalog = source("designsystem/src/commonMain/kotlin/com/quata/core/ui/components/CommunityEmojiCatalog.kt");
  const officialHost = source("feature/official/src/commonMain/kotlin/com/quata/feature/official/presentation/OfficialFeedScreenHost.kt");
  const androidUiTest = source("app/src/androidTest/java/com/quata/feature/chat/presentation/chat/ChatActionsNotificationsInstrumentedTest.kt");
  const webRunner = source("scripts/chat-actions-notifications-web-evidence.mjs");
  const androidRunner = source("scripts/chat-actions-notifications-android-evidence.mjs");
  const iosRunner = source("scripts/chat-actions-notifications-ios-evidence.mjs");
  const iosWrapper = source("scripts/run-ios-chat-actions-notifications-ui-test.sh");
  const iosUiTest = source("iosApp/iosAppUITests/QuataIosAuthenticatedChatActionsNotificationsUITests.swift");

  assert.match(catalog, /CommunityEmojiSelectorEvidenceOptInValue = "I_ACCEPT_COMMUNITY_EMOJI_SELECTOR_STATE_EVIDENCE"/);
  assert.match(catalog, /CommunityEmojiSelectorEvidenceModeEmpty = "empty"/);
  assert.match(catalog, /CommunityEmojiSelectorEvidenceModeError = "error"/);
  assert.match(catalog, /communityEmojiSelectorEvidenceCatalogState/);
  assert.match(officialHost, /communityEmojiCatalog: \(CommunityEmojiLabels, \(\(\) -> Unit\)\?\) -> CommunityEmojiCatalogState/);
  assert.match(officialHost, /slots\.communityEmojiCatalog\(strings\.emojiLabels\)/);

  for (const runner of [webRunner, androidRunner, iosRunner]) {
    assert.match(runner, /--feed-official-comments-selector-states-only/);
    assert.match(runner, /flow-emoji-selector-states-evidence/);
    assert.match(runner, /feed_comments_emoji_selector_error_state_visible_with_retry/);
    assert.match(runner, /official_comments_emoji_selector_empty_state_visible_without_cells/);
    assert.match(runner, /flow_emoji_selector_empty_and_error_states_verified_with_common_tags/);
  }

  assert.match(webRunner, /quata\.communityEmojiSelector\.optIn/);
  assert.match(webRunner, /community\.emoji\.error/);
  assert.match(webRunner, /community\.emoji\.retry/);
  assert.match(webRunner, /community\.emoji\.empty/);
  assert.match(webRunner, /feedOfficialCommentsContextualWebAnchors/);
  assert.match(webRunner, /await closeProfileSheetIfVisible\(page\);[\s\S]*await openAuthenticatedRoute\(page, origin, routeHash, routePath, \{ forceReload: true \}\)/);
  assert.match(webRunner, /const reloadQuery = options\.forceReload \? `&route-reload=\$\{Date\.now\(\)\}` : ""/);
  assert.match(webRunner, /const scope = root\?\.shadowRoot \?\? root \?\? document;[\s\S]*scope\.querySelectorAll\("\[aria-label\]"\)/);
  assert.match(webRunner, /contextualAnchor: cardTag/);
  assert.match(webRunner, /official-post-card-\$\{postId\}/);
  assert.match(webRunner, /QuataFeedActionRail portrait comments slot/);
  assert.match(webRunner, /await attachScreenshot\(page, evidenceDir, `\$\{screenshotPrefix\}-\$\{section\}`\)/);
  assert.doesNotMatch(webRunner, /feedOfficialCommentsMissingStableWebAnchors/);
  assert.doesNotMatch(webRunner, /communityEmojiPanelResetFallbacks/);
  assert.doesNotMatch(webRunner, /viewport\.width \* 0\.89/);
  assert.doesNotMatch(webRunner, /viewport\.height \* 0\.78/);
  assert.match(androidRunner, /feed-official-comments-selector-states/);
  assert.match(androidRunner, /evidenceFiles\.push\(`\$\{prefix\}-\$\{section\}\.png`\)/);
  assert.match(androidRunner, /const copiedEvidenceFiles = await collectAvailableDeviceEvidence\(evidenceDir\)/);
  assert.match(androidRunner, /report\.evidence\.files = copiedEvidenceFiles\.filter/);
  assert.match(androidUiTest, /runFeedOfficialCommentsSelectorStatesStage/);
  assert.match(androidUiTest, /quata_community_emoji_selector_evidence/);
  assert.match(androidUiTest, /community\.emoji\.error/);
  assert.match(androidUiTest, /community\.emoji\.retry/);
  assert.match(androidUiTest, /community\.emoji\.empty/);
  assert.match(androidUiTest, /sectionIndex >= 3/);
  assert.match(iosUiTest, /emojiSectionIndex\(identifier\) >= 3/);
  assert.match(iosRunner, /feedOfficialCommentsSelectorStatesOnly/);
  assert.match(iosWrapper, /QUATA_IOS_CHAT_FEED_OFFICIAL_COMMENTS_SELECTOR_STATES_UI_E2E/);
  assert.match(iosWrapper, /feed_official_comments_selector_states='QuataIosUITests\/QuataIosAuthenticatedChatActionsNotificationsUITests\/testFeedAndOfficialCommentsExposeSharedEmojiSelectorStates'/);
  assert.match(iosWrapper, /testFeedAndOfficialCommentsExposeSharedEmojiSelectorStates/);
  assert.match(iosUiTest, /testFeedAndOfficialCommentsExposeSharedEmojiSelectorStates/);
  assert.match(iosUiTest, /private let communityEmojiPanelIosEvidenceSections = \[[\s\S]*?"flags"/);
  assert.match(iosUiTest, /QUATA_IOS_COMMUNITY_EMOJI_SELECTOR_EVIDENCE_OPT_IN/);
});
