import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

const runner = await readFile(new URL("./official-editor-web-real-evidence.mjs", import.meta.url), "utf8");
const webBridge = await readFile(new URL("../web/src/wasmJsMain/kotlin/com/quata/web/WebOfficialE2eBridge.kt", import.meta.url), "utf8");
const packageJson = JSON.parse(await readFile(new URL("../package.json", import.meta.url), "utf8"));

test("Official editor Web real evidence is opt-in, redacted, and reversible", () => {
  assert.match(runner, /OFFICIAL-EDITOR-WEB-REAL-UI-001/);
  assert.match(runner, /I_ACCEPT_REVERSIBLE_OFFICIAL_POST_MUTATION/);
  assert.match(runner, /QUATA_OFFICIAL_E2E_REAL_MUTATION_OPT_IN/);
  assert.match(runner, /quata-auth-bridge/);
  assert.match(runner, /action:\s*"web_login"/);
  assert.match(runner, /quata_web_access_token/);
  assert.match(runner, /quata_web_session_token/);
  assert.match(runner, /quata_web_is_official/);
  assert.match(runner, /readAuthenticatedProfileIsOfficial/);
  assert.match(runner, /\/rest\/v1\/community_profiles/);
  assert.match(runner, /select", "is_official"/);
  assert.match(runner, /prepareOfficialProfile/);
  assert.match(runner, /forced_official_for_evidence/);
  assert.match(runner, /official_profile_role_prepared_reversibly/);
  assert.match(runner, /restoreProfileOfficialRole/);
  assert.match(runner, /permissionProfileRestore/);
  assert.match(runner, /update public\.community_profiles set is_official = true where id = \$1::uuid/);
  assert.match(runner, /official-create-action/);
  assert.match(runner, /openOfficialEditorSemantically/);
  assert.match(runner, /bridge\.create\(\)/);
  assert.match(runner, /waitForOfficialEditorState\(page, \(state\) => state\.canPublish === true\)/);
  assert.match(runner, /official_editor_invalid_draft_mutated/);
  assert.match(runner, /--media/);
  assert.match(runner, /real_\$\{options\.media\}_picker_selects_media_and_common_preview_renders/);
  assert.match(runner, /web-real-official-editor-image-preview/);
  assert.match(runner, /web-real-official-editor-video-preview/);
  assert.match(runner, /official-editor-pick-video/);
  assert.match(runner, /createMp4Fixture/);
  assert.match(runner, /play-store\/05-assets\/quata-demo-video\.mp4/);
  assert.match(runner, /async function createMp4Fixture[\s\S]*?copyFile[\s\S]*?quata-demo-video\.mp4[\s\S]*?return path;/);
  assert.doesNotMatch(runner.match(/async function createMp4Fixture[\s\S]*?return path;\n}/)?.[0] ?? "", /Buffer\.from|base64/i);
  assert.match(runner, /readCreatedRows/);
  assert.match(runner, /#official-\$\{created\.ids\[0\]\}/);
  assert.match(runner, /data-quata-shell-route/);
  assert.match(runner, /waitForCreatedOfficialPostRender\(page, created\.ids\[0\], visibleMarker, options\.evidenceDir, \(\) => createdExactReadSeen\)/);
  assert.match(runner, /created_official_post_render_missing/);
  assert.match(runner, /official-post-card-\$\{postId\}/);
  assert.match(runner, /diagnostics\.text\.includes\(visibleMarker\)/);
  assert.match(runner, /createdExactReadSeen = true/);
  assert.match(runner, /hasIdFilter[\s\S]*hasAuthorization[\s\S]*containsCreatedId/);
  assert.match(runner, /officialPublishedScreenshotHasContent/);
  assert.match(runner, /decodeRgbaPng/);
  assert.match(runner, /inflateSync/);
  assert.match(runner, /verified_in_database/);
  assert.match(runner, /visibleMarker = marker\.replace/);
  assert.match(runner, /QADATA Web \$\{visibleMarker\}/);
  assert.match(runner, /Publicacion reversible desde Web \$\{marker\}/);
  assert.match(runner, /web-real-official-post-visible-after-publish/);
  assert.match(runner, /routeDiagnostics/);
  assert.match(runner, /real_publish_focuses_created_official_route_and_captures_exact_created_card/);
  assert.match(runner, /media_url/);
  assert.match(runner, /storagePathsFromMediaUrls/);
  assert.match(runner, /wordpressVideoUrlsFromMediaUrls/);
  assert.match(runner, /cleanupStorageObjects/);
  assert.match(runner, /cleanupWordpressVideoUrls/);
  assert.match(runner, /assertWordpressVideoUrlsAbsent/);
  assert.match(runner, /wordpressPostCleanupReadback/);
  assert.match(runner, /wordpress_post_cleanup_verification_failed/);
  assert.match(runner, /\[404,\s*410\]\.includes\(response\.status\)/);
  assert.match(runner, /quqos_delete_post_video/);
  assert.match(runner, /wordpressBaseUrl/);
  assert.match(runner, /wordpress-proxy/);
  assert.match(runner, /proxyWordpressRequest/);
  assert.match(runner, /sanitizeMediaResponse/);
  assert.match(runner, /scrollIntoViewIfNeeded/);
  assert.match(runner, /locator\.click\(\{ force: true/);
  assert.match(runner, /officialEditorAction\(page, "setAdvancedMode"\)/);
  assert.match(runner, /officialEditorAction\(page, "setTitle", titleText\)/);
  assert.match(runner, /officialEditorAction\(page, "setSummary", summaryText\)/);
  assert.match(runner, /officialEditorAction\(page, "setBodyHtml"/);
  assert.match(runner, /clickVisibleProductElement\(page, "official-editor-publish"\)/);
  assert.doesNotMatch(runner, /officialEditorAction\(page, "publish"\)/);
  assert.doesNotMatch(webBridge, /publishAnchor/);
  assert.doesNotMatch(webBridge, /publish: \(\) => publish\(\)/);
  assert.doesNotMatch(webBridge, /publish\(\);/);
  assert.match(runner, /async function clickVisibleProductElement\(page, id\)/);
  assert.match(runner, /clickWebWasmVisualPublishFallback\(page\)/);
  assert.match(runner, /web_wasm_publish_dom_anchor_missing_visual_canvas_fallback_used/);
  assert.match(runner, /findOrangePublishButton\(buffer\)/);
  assert.match(runner, /reason: "wasm_compose_test_tag_not_exposed_as_dom_anchor"/);
  assert.match(runner, /await page\.mouse\.click\(target\.center\.x, target\.center\.y\)/);
  assert.match(runner, /assertVisibleBox\(box, `missing_visible_product_anchor:\$\{id\}`\)/);
  assert.match(runner, /await locator\.click\(\{ timeout: 5_000 \}\)/);
  const visibleProductClickHelper = runner.slice(
    runner.indexOf("async function clickVisibleProductElement(page, id)"),
    runner.indexOf("async function clickWebWasmVisualPublishFallback(page)"),
  );
  assert.doesNotMatch(visibleProductClickHelper, /dispatchEvent|force:\s*true|officialEditorAction/);
  assert.match(runner, /missing_web_wasm_visual_publish_anchor/);
  assert.match(runner, /official-editor-preview/);
  assert.match(runner, /waitFor\(\{ state: "attached"/);
  assert.match(runner, /Number\(state\.bodyLength \?\? 0\) > 0/);
  assert.match(runner, /web-real-official-editor-filled/);
  assert.match(runner, /waitForTimeout\(500\)/);
  assert.doesNotMatch(runner, /#official-editor-preview[\s\S]*?getByText\(new RegExp\(escapeRegExp\(visibleMarker\)\)\)/);
  assert.match(runner, /clickTranslationSingleLanguageIfShown/);
  assert.match(runner, /Publicar solo este idioma/);
  assert.match(runner, /shared_fasttext_translation_prompt_skipped_for_reversible_single_language_publish/);
  assert.doesNotMatch(runner, /globalThis\.prompt|window\.prompt|page\.once\("dialog"|dialog\.accept/);
  assert.match(runner, /isIgnorablePublishedVideoCorsFault/);
  assert.match(runner, /egquata\\\.com\\\/wp-content\\\/uploads/);
  assert.match(runner, /ignoredRuntimeFaults/);
  assert.match(runner, /storage\/v1\/object\/community-posts/);
  assert.match(runner, /assertStorageObjectsAbsent/);
  assert.match(runner, /from storage\.objects/);
  assert.match(runner, /name = any\(\$1::text\[\]\)/);
  assert.match(runner, /delete from public\.official_posts/);
  assert.match(runner, /values:\s*\[ids, groupIds\]/);
  assert.match(runner, /assertNoMarkerRows/);
  assert.match(runner, /marker_cleanup_verification_failed/);
  assert.doesNotMatch(runner, /SERVICE_ROLE|21085800|\+240|68024260/);
});

test("Official editor Web real evidence is callable but kept out of automatic fast CI mutation gates", () => {
  assert.match(packageJson.scripts["evidence:web-official-editor-real"], /scripts\/official-editor-web-real-evidence\.mjs/);
  assert.match(packageJson.scripts["evidence:web-official-editor-real-media"], /--media image/);
  assert.match(packageJson.scripts["evidence:web-official-editor-real-video"], /--media video/);
  assert.match(packageJson.scripts["test:ci-fast-contracts"], /scripts\/official-editor-web-real-evidence-contract\.test\.mjs/);
  assert.match(packageJson.scripts["test:web-wave2-contracts"], /scripts\/official-editor-web-real-evidence-contract\.test\.mjs/);
  assert.doesNotMatch(packageJson.scripts["test:ci-fast-contracts"], /official-editor-web-real-evidence\.mjs --/);
});
