import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

const runner = await readFile(new URL("./official-editor-web-real-evidence.mjs", import.meta.url), "utf8");
const packageJson = JSON.parse(await readFile(new URL("../package.json", import.meta.url), "utf8"));

test("Official editor Web real evidence is opt-in, redacted, and reversible", () => {
  assert.match(runner, /OFFICIAL-EDITOR-WEB-REAL-UI-001/);
  assert.match(runner, /I_ACCEPT_REVERSIBLE_OFFICIAL_POST_MUTATION/);
  assert.match(runner, /QUATA_OFFICIAL_E2E_REAL_MUTATION_OPT_IN/);
  assert.match(runner, /quata-auth-bridge/);
  assert.match(runner, /action:\s*"web_login"/);
  assert.match(runner, /quata_web_access_token/);
  assert.match(runner, /quata_web_session_token/);
  assert.match(runner, /official_editor_invalid_draft_mutated/);
  assert.match(runner, /--media/);
  assert.match(runner, /real_\$\{options\.media\}_picker_selects_media_and_common_preview_renders/);
  assert.match(runner, /web-real-official-editor-image-preview/);
  assert.match(runner, /web-real-official-editor-video-preview/);
  assert.match(runner, /official-editor-pick-video/);
  assert.match(runner, /createMp4Fixture/);
  assert.match(runner, /play-store\/05-assets\/quata-demo-video\.mp4/);
  assert.match(runner, /async function createMp4Fixture[\s\S]*?copyFile[\s\S]*?quata-demo-video\.mp4[\s\S]*?return path;/);
  assert.doesNotMatch(runner.match(/async function createMp4Fixture[\s\S]*?return path;\n}/)?.[0] ?? "", /Buffer\.from|base64/i);
  assert.match(runner, /readCreatedRows/);
  assert.match(runner, /media_url/);
  assert.match(runner, /storagePathsFromMediaUrls/);
  assert.match(runner, /wordpressVideoUrlsFromMediaUrls/);
  assert.match(runner, /cleanupStorageObjects/);
  assert.match(runner, /cleanupWordpressVideoUrls/);
  assert.match(runner, /assertWordpressVideoUrlsAbsent/);
  assert.match(runner, /wordpressPostCleanupReadback/);
  assert.match(runner, /wordpress_post_cleanup_verification_failed/);
  assert.match(runner, /\[404,\s*410\]\.includes\(response\.status\)/);
  assert.match(runner, /quqos_delete_post_video/);
  assert.match(runner, /wordpressBaseUrl/);
  assert.match(runner, /wordpress-proxy/);
  assert.match(runner, /proxyWordpressRequest/);
  assert.match(runner, /sanitizeMediaResponse/);
  assert.match(runner, /scrollIntoViewIfNeeded/);
  assert.match(runner, /locator\.click\(\{ force: true/);
  assert.match(runner, /isIgnorablePublishedVideoCorsFault/);
  assert.match(runner, /egquata\\\.com\\\/wp-content\\\/uploads/);
  assert.match(runner, /ignoredRuntimeFaults/);
  assert.match(runner, /storage\/v1\/object\/community-posts/);
  assert.match(runner, /assertStorageObjectsAbsent/);
  assert.match(runner, /from storage\.objects/);
  assert.match(runner, /name = any\(\$1::text\[\]\)/);
  assert.match(runner, /delete from public\.official_posts/);
  assert.match(runner, /values:\s*\[ids, groupIds\]/);
  assert.match(runner, /assertNoMarkerRows/);
  assert.match(runner, /marker_cleanup_verification_failed/);
  assert.doesNotMatch(runner, /SERVICE_ROLE|21085800|\+240|68024260/);
});

test("Official editor Web real evidence is callable but kept out of automatic fast CI mutation gates", () => {
  assert.match(packageJson.scripts["evidence:web-official-editor-real"], /scripts\/official-editor-web-real-evidence\.mjs/);
  assert.match(packageJson.scripts["evidence:web-official-editor-real-media"], /--media image/);
  assert.match(packageJson.scripts["evidence:web-official-editor-real-video"], /--media video/);
  assert.match(packageJson.scripts["test:ci-fast-contracts"], /scripts\/official-editor-web-real-evidence-contract\.test\.mjs/);
  assert.match(packageJson.scripts["test:web-wave2-contracts"], /scripts\/official-editor-web-real-evidence-contract\.test\.mjs/);
  assert.doesNotMatch(packageJson.scripts["test:ci-fast-contracts"], /official-editor-web-real-evidence\.mjs --/);
});
