import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";
import { buildPurgePlan, manifestDigest, redactedEvidence, sha256, validateManifest } from "./web-chat-exact-purge-gate.mjs";

const runId = "11111111-1111-4111-8111-111111111111", a = "22222222-2222-4222-8222-222222222222", b = "33333333-3333-4333-8333-333333333333", pa = "44444444-4444-4444-8444-444444444444", pb = "55555555-5555-4555-8555-555555555555";
const candidateSha = "c".repeat(64), projectRef = "test-project-001";
function manifest() { const m = { schemaVersion: 2, run_id: runId, candidate_sha: candidateSha, purpose: "isolated_sb04_chat_fixture_purge", database: { project_ref: projectRef }, auth_user_ids: [a,b], profile_ids: [pa,pb], attachments: [], fixtures: [{run_id:runId,auth_user_id:a,profile_id:pa,scope:"isolated_sb04_account"},{run_id:runId,auth_user_id:b,profile_id:pb,scope:"isolated_sb04_account"}], provenance:{source:"web-chat-browser-e2e",run_id:runId,candidate_sha:candidateSha} }; m.provenance.manifest_sha256=manifestDigest(m); return m; }
function input(m=manifest()) { return { manifest:m, expectedRunId:runId, expectedManifestSha256:manifestDigest(m), candidateSha, expectedProjectRef:projectRef, constraints:[{child_schema:"public",child_table:"chat_messages",child_column:"sender_profile_id",parent_schema:"public",parent_table:"community_profiles",parent_column:"id",delete_rule:"c"}], snapshots:["chat_threads","chat_private_threads","chat_participants","chat_messages","chat_attachments","chat_message_favorites","chat_message_reactions","chat_message_reads","chat_profile_blocks","chat_events","chat_sos_events","chat_sos_recipients","push_tokens","push_delivery_log","web_client_sessions","web_push_subscriptions","web_push_delivery_log","account_deletion_requests","community_profiles","auth.users"].map(table=>({table,count:0})), fingerprint:{project_ref:projectRef,server_version_num:"160001",database:"postgres",server_endpoint:"127.0.0.1:5432"} }; }
test("frozen two-account manifest and graph produce redacted read-only evidence", () => { const plan=buildPurgePlan(input()); assert.equal(plan.deleteOrder.at(-1),"auth.users"); assert.equal(redactedEvidence(plan).destructiveAuthorization,"unavailable_by_construction"); });
test("injection, file swap, wrong project, forged/replay provenance and attachments reject", () => { for(const mutate of [m=>m.profile_ids[0]=`${pa}';delete from auth.users;--`,m=>m.database.project_ref="other-project-002",m=>m.provenance.candidate_sha="d".repeat(64),m=>m.provenance.run_id="66666666-6666-4666-8666-666666666666",m=>m.attachments=[{bucket:"x",path:"x"}]]) { const m=manifest(); mutate(m); const x=input(m); x.expectedManifestSha256=manifestDigest(m); assert.throws(()=>buildPurgePlan(x),/purge_/); } const x=input(); x.manifest.fixtures[0].profile_id=pb; assert.throws(()=>validateManifest(x.manifest,x),/purge_manifest_hash_mismatch/); });
test("unknown FK, restriction and partial counts fail closed", () => { for(const row of [{child_schema:"public",child_table:"chat_messages",child_column:"sender_profile_id",parent_schema:"public",parent_table:"community_profiles",parent_column:"id",delete_rule:"r"},{child_schema:"public",child_table:"evil",child_column:"profile_id",parent_schema:"public",parent_table:"community_profiles",parent_column:"id",delete_rule:"c"},{child_schema:"public",child_table:"chat_messages",child_column:"tenant_id",parent_schema:"public",parent_table:"community_profiles",parent_column:"id",delete_rule:"c"}]) {const x=input();x.constraints=[row];assert.throws(()=>buildPurgePlan(x),/purge_fk_/);} const x=input();x.snapshots.pop();assert.throws(()=>buildPurgePlan(x),/purge_snapshot/); });
test("wrapper validates first, uses temp UUID tables and can never commit", async () => { const w=await readFile(new URL("./run-web-chat-exact-purge-gate.ps1",import.meta.url),"utf8"); for(const token of ["purge_commit_unavailable_by_construction","--validate-manifest","CREATE TEMP TABLE purge_profiles","CREATE TEMP TABLE purge_auth_users","\\\\copy purge_profiles","SERIALIZABLE READ ONLY","pg_advisory_xact_lock","lock_timeout","statement_timeout","ROLLBACK","PGSERVICEFILE","PGPASSFILE"]) assert.match(w,new RegExp(token)); assert.doesNotMatch(w,/delete\s+from|quata_account_delete_data|psql\s+\$dbUrl/i); });
