begin;

create table if not exists public.ugc_reports (
  id bigint generated by default as identity primary key,
  reporter_profile_id uuid not null references public.community_profiles(id) on delete cascade,
  target_type text not null check (target_type in (
    'community_post', 'official_post', 'community_comment',
    'official_comment', 'chat_message', 'profile'
  )),
  target_id text not null,
  reported_profile_id uuid references public.community_profiles(id) on delete set null,
  reason text not null check (reason in (
    'child_safety', 'harassment', 'hate', 'sexual', 'violence',
    'spam', 'impersonation', 'other'
  )),
  details text,
  status text not null default 'pending' check (status in ('pending', 'reviewing', 'actioned', 'dismissed')),
  created_at timestamptz not null default now(),
  reviewed_at timestamptz,
  reviewed_by uuid references public.community_profiles(id) on delete set null,
  constraint ugc_reports_target_not_blank check (btrim(target_id) <> ''),
  constraint ugc_reports_details_length check (details is null or char_length(details) <= 1000),
  unique (reporter_profile_id, target_type, target_id)
);

create index if not exists ugc_reports_pending_created_idx
  on public.ugc_reports (created_at) where status = 'pending';
create index if not exists ugc_reports_reported_profile_idx
  on public.ugc_reports (reported_profile_id, created_at desc);

alter table public.ugc_reports enable row level security;

drop policy if exists "Reporters can read their reports" on public.ugc_reports;
create policy "Reporters can read their reports"
  on public.ugc_reports for select
  using (reporter_profile_id = public.quata_chat_actor_profile_id(reporter_profile_id));

create table if not exists public.ugc_terms_acceptances (
  profile_id uuid not null references public.community_profiles(id) on delete cascade,
  terms_version text not null,
  accepted_at timestamptz not null default now(),
  primary key (profile_id, terms_version),
  constraint ugc_terms_version_not_blank check (btrim(terms_version) <> '')
);

alter table public.ugc_terms_acceptances enable row level security;

drop policy if exists "Users can read their terms acceptances" on public.ugc_terms_acceptances;
create policy "Users can read their terms acceptances"
  on public.ugc_terms_acceptances for select
  using (profile_id = public.quata_chat_actor_profile_id(profile_id));

create or replace function public.quata_ugc_report(
  p_actor_profile_id uuid,
  p_target_type text,
  p_target_id text,
  p_reason text,
  p_details text default null
) returns jsonb
language plpgsql security definer set search_path = public
as $$
declare
  v_actor uuid;
  v_reported uuid;
  v_report_id bigint;
begin
  v_actor := public.quata_chat_actor_profile_id(p_actor_profile_id);
  if v_actor is null then raise exception 'Not authenticated'; end if;
  if p_reason not in ('child_safety','harassment','hate','sexual','violence','spam','impersonation','other') then
    raise exception 'Invalid report reason';
  end if;

  case p_target_type
    when 'community_post' then
      select profile_id into v_reported from public.community_posts where id = p_target_id::uuid;
    when 'official_post' then
      select profile_id into v_reported from public.official_posts where id = p_target_id::uuid and deleted_at is null;
    when 'community_comment' then
      select profile_id into v_reported from public.community_comments where id = p_target_id::uuid;
    when 'official_comment' then
      select profile_id into v_reported from public.official_post_comments where id = p_target_id::uuid;
    when 'chat_message' then
      select sender_profile_id into v_reported from public.chat_messages m
      where m.id = p_target_id::bigint and exists (
        select 1 from public.chat_participants cp
        where cp.thread_id = m.thread_id and cp.profile_id = v_actor and cp.left_at is null
      );
    when 'profile' then
      select id into v_reported from public.community_profiles where id = p_target_id::uuid;
    else
      raise exception 'Invalid report target';
  end case;

  if v_reported is null then raise exception 'Report target not found or unavailable'; end if;
  if v_reported = v_actor then raise exception 'You cannot report your own content'; end if;

  insert into public.ugc_reports (
    reporter_profile_id, target_type, target_id, reported_profile_id, reason, details
  ) values (
    v_actor, p_target_type, p_target_id, v_reported, p_reason, nullif(btrim(p_details), '')
  )
  on conflict (reporter_profile_id, target_type, target_id) do update
    set reason = excluded.reason,
        details = excluded.details,
        status = 'pending',
        created_at = now(),
        reviewed_at = null,
        reviewed_by = null
  returning id into v_report_id;

  return jsonb_build_object('ok', true, 'report_id', v_report_id);
end;
$$;

create or replace function public.quata_profile_block(
  p_actor_profile_id uuid,
  p_profile_id uuid
) returns jsonb
language plpgsql security definer set search_path = public
as $$
declare v_actor uuid;
begin
  v_actor := public.quata_chat_actor_profile_id(p_actor_profile_id);
  if v_actor is null then raise exception 'Not authenticated'; end if;
  if v_actor = p_profile_id then raise exception 'You cannot block yourself'; end if;
  if not exists (select 1 from public.community_profiles where id = p_profile_id) then
    raise exception 'Profile not found';
  end if;
  if not exists (
    select 1 from public.chat_profile_blocks
    where thread_id is null and blocker_profile_id = v_actor and blocked_profile_id = p_profile_id
  ) then
    insert into public.chat_profile_blocks(thread_id, blocker_profile_id, blocked_profile_id)
    values (null, v_actor, p_profile_id);
  end if;
  return jsonb_build_object('ok', true);
end;
$$;

create or replace function public.quata_profile_unblock(
  p_actor_profile_id uuid,
  p_profile_id uuid
) returns jsonb
language plpgsql security definer set search_path = public
as $$
declare v_actor uuid;
begin
  v_actor := public.quata_chat_actor_profile_id(p_actor_profile_id);
  if v_actor is null then raise exception 'Not authenticated'; end if;
  delete from public.chat_profile_blocks
  where thread_id is null and blocker_profile_id = v_actor and blocked_profile_id = p_profile_id;
  return jsonb_build_object('ok', true);
end;
$$;

create or replace function public.quata_has_accepted_ugc_terms(
  p_actor_profile_id uuid,
  p_terms_version text
) returns boolean
language sql security definer set search_path = public stable
as $$
  select exists (
    select 1 from public.ugc_terms_acceptances
    where profile_id = public.quata_chat_actor_profile_id(p_actor_profile_id)
      and terms_version = p_terms_version
  );
$$;

create or replace function public.quata_accept_ugc_terms(
  p_actor_profile_id uuid,
  p_terms_version text
) returns jsonb
language plpgsql security definer set search_path = public
as $$
declare v_actor uuid;
begin
  v_actor := public.quata_chat_actor_profile_id(p_actor_profile_id);
  if v_actor is null then raise exception 'Not authenticated'; end if;
  if btrim(p_terms_version) = '' then raise exception 'Invalid terms version'; end if;
  insert into public.ugc_terms_acceptances(profile_id, terms_version)
  values (v_actor, p_terms_version)
  on conflict (profile_id, terms_version) do update set accepted_at = now();
  return jsonb_build_object('ok', true);
end;
$$;

revoke all on function public.quata_ugc_report(uuid,text,text,text,text) from public;
revoke all on function public.quata_profile_block(uuid,uuid) from public;
revoke all on function public.quata_profile_unblock(uuid,uuid) from public;
revoke all on function public.quata_has_accepted_ugc_terms(uuid,text) from public;
revoke all on function public.quata_accept_ugc_terms(uuid,text) from public;
grant execute on function public.quata_ugc_report(uuid,text,text,text,text) to authenticated;
grant execute on function public.quata_profile_block(uuid,uuid) to authenticated;
grant execute on function public.quata_profile_unblock(uuid,uuid) to authenticated;
grant execute on function public.quata_has_accepted_ugc_terms(uuid,text) to authenticated;
grant execute on function public.quata_accept_ugc_terms(uuid,text) to authenticated;

commit;
