-- Quata chat schema for replacing Better Messages with Supabase.
-- Identity model:
-- - The app currently treats public.community_profiles.id as the logged-in user id.
-- - If Supabase Auth is wired later, fill community_profiles.auth_user_id with auth.users.id.
-- - RPC functions in the next migration accept p_actor_profile_id for current app compatibility.

create extension if not exists pgcrypto;

alter table public.community_profiles
    add column if not exists auth_user_id uuid;

do $$
begin
    if not exists (
        select 1
        from pg_constraint
        where conname = 'community_profiles_auth_user_id_fkey'
    ) then
        alter table public.community_profiles
            add constraint community_profiles_auth_user_id_fkey
            foreign key (auth_user_id) references auth.users(id) on delete set null;
    end if;
end $$;

create unique index if not exists community_profiles_auth_user_id_key
    on public.community_profiles(auth_user_id)
    where auth_user_id is not null;

create table if not exists public.chat_threads (
    id bigint generated by default as identity primary key,
    type text not null default 'private',
    subject text,
    title text,
    image_url text,
    community_id uuid references public.community_walls(id) on delete set null,
    created_by_profile_id uuid not null references public.community_profiles(id) on delete cascade,
    unique_key text,
    allow_invite boolean not null default true,
    metadata jsonb not null default '{}'::jsonb,
    last_message_at timestamptz,
    last_message_preview text not null default '',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    deleted_at timestamptz,
    constraint chat_threads_type_check
        check (type in ('private', 'group', 'wall', 'sos'))
);

create unique index if not exists chat_threads_unique_key_idx
    on public.chat_threads(unique_key)
    where unique_key is not null;

create index if not exists chat_threads_community_id_idx on public.chat_threads(community_id);
create index if not exists chat_threads_last_message_at_idx on public.chat_threads(last_message_at desc nulls last);
create index if not exists chat_threads_updated_at_idx on public.chat_threads(updated_at desc);

create table if not exists public.chat_private_threads (
    thread_id bigint primary key references public.chat_threads(id) on delete cascade,
    profile_low_id uuid not null references public.community_profiles(id) on delete cascade,
    profile_high_id uuid not null references public.community_profiles(id) on delete cascade,
    created_at timestamptz not null default now(),
    constraint chat_private_threads_distinct_profiles_check check (profile_low_id <> profile_high_id),
    constraint chat_private_threads_order_check check (profile_low_id < profile_high_id),
    constraint chat_private_threads_pair_key unique (profile_low_id, profile_high_id)
);

create table if not exists public.chat_participants (
    thread_id bigint not null references public.chat_threads(id) on delete cascade,
    profile_id uuid not null references public.community_profiles(id) on delete cascade,
    role text not null default 'member',
    joined_at timestamptz not null default now(),
    left_at timestamptz,
    is_hidden boolean not null default false,
    is_deleted boolean not null default false,
    muted_at timestamptz,
    pinned_at timestamptz,
    last_read_at timestamptz,
    last_read_message_id bigint,
    metadata jsonb not null default '{}'::jsonb,
    primary key (thread_id, profile_id),
    constraint chat_participants_role_check check (role in ('owner', 'moderator', 'member'))
);

create index if not exists chat_participants_profile_idx
    on public.chat_participants(profile_id, is_deleted, is_hidden, left_at);
create index if not exists chat_participants_thread_idx on public.chat_participants(thread_id);

create table if not exists public.chat_messages (
    id bigint generated by default as identity primary key,
    thread_id bigint not null references public.chat_threads(id) on delete cascade,
    sender_profile_id uuid not null references public.community_profiles(id) on delete cascade,
    body text not null default '',
    client_message_id text,
    reply_to_message_id bigint references public.chat_messages(id) on delete set null,
    forwarded_from_message_id bigint references public.chat_messages(id) on delete set null,
    forwarded_from_profile_id uuid references public.community_profiles(id) on delete set null,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz,
    edited_at timestamptz,
    deleted_at timestamptz,
    deleted_by_profile_id uuid references public.community_profiles(id) on delete set null
);

create index if not exists chat_messages_thread_created_idx
    on public.chat_messages(thread_id, created_at, id);
create index if not exists chat_messages_thread_updated_idx
    on public.chat_messages(thread_id, coalesce(updated_at, edited_at, created_at) desc);
create index if not exists chat_messages_sender_idx on public.chat_messages(sender_profile_id);
create index if not exists chat_messages_reply_idx on public.chat_messages(reply_to_message_id);
create unique index if not exists chat_messages_client_message_unique_idx
    on public.chat_messages(thread_id, sender_profile_id, client_message_id)
    where client_message_id is not null;

create table if not exists public.chat_attachments (
    id bigint generated by default as identity primary key,
    thread_id bigint not null references public.chat_threads(id) on delete cascade,
    message_id bigint references public.chat_messages(id) on delete cascade,
    uploaded_by_profile_id uuid not null references public.community_profiles(id) on delete cascade,
    storage_bucket text,
    storage_path text,
    file_url text not null,
    thumb jsonb,
    mime_type text,
    file_name text,
    size_bytes bigint,
    ext text,
    created_at timestamptz not null default now(),
    attached_at timestamptz
);

create index if not exists chat_attachments_thread_idx on public.chat_attachments(thread_id);
create index if not exists chat_attachments_message_idx on public.chat_attachments(message_id);
create index if not exists chat_attachments_uploaded_by_idx on public.chat_attachments(uploaded_by_profile_id);

create table if not exists public.chat_message_favorites (
    profile_id uuid not null references public.community_profiles(id) on delete cascade,
    message_id bigint not null references public.chat_messages(id) on delete cascade,
    created_at timestamptz not null default now(),
    primary key (profile_id, message_id)
);

create index if not exists chat_message_favorites_message_idx
    on public.chat_message_favorites(message_id);

create table if not exists public.chat_message_reactions (
    id bigint generated by default as identity primary key,
    message_id bigint not null references public.chat_messages(id) on delete cascade,
    profile_id uuid not null references public.community_profiles(id) on delete cascade,
    reaction_type text not null,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    constraint chat_message_reactions_unique unique (message_id, profile_id, reaction_type)
);

create table if not exists public.chat_message_reads (
    message_id bigint not null references public.chat_messages(id) on delete cascade,
    profile_id uuid not null references public.community_profiles(id) on delete cascade,
    read_at timestamptz not null default now(),
    primary key (message_id, profile_id)
);

create index if not exists chat_message_reads_profile_idx
    on public.chat_message_reads(profile_id, read_at desc);

create table if not exists public.chat_profile_blocks (
    id bigint generated by default as identity primary key,
    thread_id bigint references public.chat_threads(id) on delete cascade,
    blocker_profile_id uuid not null references public.community_profiles(id) on delete cascade,
    blocked_profile_id uuid not null references public.community_profiles(id) on delete cascade,
    created_at timestamptz not null default now(),
    constraint chat_profile_blocks_no_self_check check (blocker_profile_id <> blocked_profile_id)
);

create unique index if not exists chat_profile_blocks_thread_key
    on public.chat_profile_blocks(thread_id, blocker_profile_id, blocked_profile_id)
    where thread_id is not null;
create unique index if not exists chat_profile_blocks_global_key
    on public.chat_profile_blocks(blocker_profile_id, blocked_profile_id)
    where thread_id is null;

create table if not exists public.chat_events (
    id bigint generated by default as identity primary key,
    thread_id bigint references public.chat_threads(id) on delete cascade,
    actor_profile_id uuid references public.community_profiles(id) on delete set null,
    event_type text not null,
    payload jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);

create index if not exists chat_events_thread_created_idx
    on public.chat_events(thread_id, created_at desc);

create table if not exists public.chat_sos_events (
    id uuid primary key default gen_random_uuid(),
    thread_id bigint references public.chat_threads(id) on delete set null,
    profile_id uuid not null references public.community_profiles(id) on delete cascade,
    message_id bigint references public.chat_messages(id) on delete set null,
    message text not null,
    latitude double precision,
    longitude double precision,
    accuracy_m double precision,
    sent_count integer not null default 0,
    created_at timestamptz not null default now()
);

create table if not exists public.chat_sos_recipients (
    sos_event_id uuid not null references public.chat_sos_events(id) on delete cascade,
    recipient_profile_id uuid not null references public.community_profiles(id) on delete cascade,
    delivered_thread_id bigint references public.chat_threads(id) on delete set null,
    created_at timestamptz not null default now(),
    primary key (sos_event_id, recipient_profile_id)
);

create index if not exists chat_sos_events_profile_created_idx
    on public.chat_sos_events(profile_id, created_at desc);
create index if not exists chat_sos_recipients_recipient_idx
    on public.chat_sos_recipients(recipient_profile_id, created_at desc);

create or replace function public.quata_chat_touch_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists chat_threads_touch_updated_at on public.chat_threads;
create trigger chat_threads_touch_updated_at
before update on public.chat_threads
for each row
execute function public.quata_chat_touch_updated_at();

create or replace function public.quata_chat_refresh_thread_summary(p_thread_id bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
    v_last record;
begin
    select m.created_at, left(coalesce(m.body, ''), 500) as preview
    into v_last
    from public.chat_messages m
    where m.thread_id = p_thread_id
      and m.deleted_at is null
    order by m.created_at desc, m.id desc
    limit 1;

    update public.chat_threads t
    set last_message_at = v_last.created_at,
        last_message_preview = coalesce(v_last.preview, ''),
        updated_at = now()
    where t.id = p_thread_id;
end;
$$;

create or replace function public.quata_chat_message_after_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
    v_thread_id bigint;
begin
    v_thread_id = coalesce(new.thread_id, old.thread_id);
    perform public.quata_chat_refresh_thread_summary(v_thread_id);
    if tg_op = 'DELETE' then
        return old;
    end if;
    return new;
end;
$$;

drop trigger if exists chat_messages_after_insert_refresh_thread on public.chat_messages;
create trigger chat_messages_after_insert_refresh_thread
after insert on public.chat_messages
for each row
execute function public.quata_chat_message_after_change();

drop trigger if exists chat_messages_after_update_refresh_thread on public.chat_messages;
create trigger chat_messages_after_update_refresh_thread
after update on public.chat_messages
for each row
execute function public.quata_chat_message_after_change();

create or replace function public.quata_chat_participant_after_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
    update public.chat_threads
    set updated_at = now()
    where id = coalesce(new.thread_id, old.thread_id);
    if tg_op = 'DELETE' then
        return old;
    end if;
    return new;
end;
$$;

drop trigger if exists chat_participants_after_change_touch_thread on public.chat_participants;
create trigger chat_participants_after_change_touch_thread
after insert or update or delete on public.chat_participants
for each row
execute function public.quata_chat_participant_after_change();

create or replace function public.quata_chat_auth_profile_id()
returns uuid
language sql
stable
security definer
set search_path = public, auth
as $$
    select cp.id
    from public.community_profiles cp
    where auth.uid() is not null
      and (cp.id = auth.uid() or cp.auth_user_id = auth.uid())
    limit 1
$$;

create or replace function public.quata_chat_actor_profile_id(p_actor_profile_id uuid default null)
returns uuid
language plpgsql
stable
security definer
set search_path = public, auth
as $$
declare
    v_auth_profile_id uuid;
begin
    v_auth_profile_id := public.quata_chat_auth_profile_id();

    if v_auth_profile_id is not null then
        if p_actor_profile_id is not null and p_actor_profile_id <> v_auth_profile_id then
            raise exception 'actor profile does not match authenticated Supabase user'
                using errcode = '42501';
        end if;
        return v_auth_profile_id;
    end if;

    -- Compatibility path for the current Android client, which stores
    -- AuthSession.token = 'supabase-profile:<community_profiles.id>' and
    -- calls Supabase with the anon key.
    if p_actor_profile_id is not null then
        if exists (select 1 from public.community_profiles where id = p_actor_profile_id) then
            return p_actor_profile_id;
        end if;
        raise exception 'actor profile does not exist' using errcode = '42501';
    end if;

    raise exception 'actor profile is required' using errcode = '42501';
end;
$$;

create or replace function public.quata_chat_is_thread_participant(
    p_thread_id bigint,
    p_profile_id uuid
)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
    select exists (
        select 1
        from public.chat_participants p
        where p.thread_id = p_thread_id
          and p.profile_id = p_profile_id
          and p.left_at is null
    )
$$;

create or replace function public.quata_chat_can_moderate(
    p_thread_id bigint,
    p_profile_id uuid
)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
    select exists (
        select 1
        from public.chat_participants p
        where p.thread_id = p_thread_id
          and p.profile_id = p_profile_id
          and p.left_at is null
          and p.role in ('owner', 'moderator')
    )
$$;

create or replace function public.quata_chat_is_blocked(
    p_thread_id bigint,
    p_sender_profile_id uuid,
    p_target_profile_id uuid
)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
    select exists (
        select 1
        from public.chat_profile_blocks b
        where b.blocker_profile_id = p_target_profile_id
          and b.blocked_profile_id = p_sender_profile_id
          and (b.thread_id is null or b.thread_id = p_thread_id)
    )
$$;

alter table public.chat_threads enable row level security;
alter table public.chat_private_threads enable row level security;
alter table public.chat_participants enable row level security;
alter table public.chat_messages enable row level security;
alter table public.chat_attachments enable row level security;
alter table public.chat_message_favorites enable row level security;
alter table public.chat_message_reactions enable row level security;
alter table public.chat_message_reads enable row level security;
alter table public.chat_profile_blocks enable row level security;
alter table public.chat_events enable row level security;
alter table public.chat_sos_events enable row level security;
alter table public.chat_sos_recipients enable row level security;

drop policy if exists chat_threads_select_participants on public.chat_threads;
create policy chat_threads_select_participants
on public.chat_threads
for select
to authenticated
using (
    public.quata_chat_is_thread_participant(id, public.quata_chat_auth_profile_id())
);

drop policy if exists chat_private_threads_select_participants on public.chat_private_threads;
create policy chat_private_threads_select_participants
on public.chat_private_threads
for select
to authenticated
using (
    public.quata_chat_is_thread_participant(thread_id, public.quata_chat_auth_profile_id())
);

drop policy if exists chat_participants_select_thread_participants on public.chat_participants;
create policy chat_participants_select_thread_participants
on public.chat_participants
for select
to authenticated
using (
    public.quata_chat_is_thread_participant(thread_id, public.quata_chat_auth_profile_id())
);

drop policy if exists chat_messages_select_thread_participants on public.chat_messages;
create policy chat_messages_select_thread_participants
on public.chat_messages
for select
to authenticated
using (
    public.quata_chat_is_thread_participant(thread_id, public.quata_chat_auth_profile_id())
);

drop policy if exists chat_attachments_select_thread_participants on public.chat_attachments;
create policy chat_attachments_select_thread_participants
on public.chat_attachments
for select
to authenticated
using (
    public.quata_chat_is_thread_participant(thread_id, public.quata_chat_auth_profile_id())
);

drop policy if exists chat_message_favorites_select_own on public.chat_message_favorites;
create policy chat_message_favorites_select_own
on public.chat_message_favorites
for select
to authenticated
using (profile_id = public.quata_chat_auth_profile_id());

drop policy if exists chat_message_reactions_select_thread_participants on public.chat_message_reactions;
create policy chat_message_reactions_select_thread_participants
on public.chat_message_reactions
for select
to authenticated
using (
    exists (
        select 1
        from public.chat_messages m
        where m.id = message_id
          and public.quata_chat_is_thread_participant(m.thread_id, public.quata_chat_auth_profile_id())
    )
);

drop policy if exists chat_message_reads_select_thread_participants on public.chat_message_reads;
create policy chat_message_reads_select_thread_participants
on public.chat_message_reads
for select
to authenticated
using (
    exists (
        select 1
        from public.chat_messages m
        where m.id = message_id
          and public.quata_chat_is_thread_participant(m.thread_id, public.quata_chat_auth_profile_id())
    )
);

drop policy if exists chat_profile_blocks_select_own on public.chat_profile_blocks;
create policy chat_profile_blocks_select_own
on public.chat_profile_blocks
for select
to authenticated
using (
    blocker_profile_id = public.quata_chat_auth_profile_id()
    or blocked_profile_id = public.quata_chat_auth_profile_id()
);

drop policy if exists chat_events_select_thread_participants on public.chat_events;
create policy chat_events_select_thread_participants
on public.chat_events
for select
to authenticated
using (
    thread_id is not null
    and public.quata_chat_is_thread_participant(thread_id, public.quata_chat_auth_profile_id())
);

drop policy if exists chat_sos_events_select_owner_or_recipient on public.chat_sos_events;
create policy chat_sos_events_select_owner_or_recipient
on public.chat_sos_events
for select
to authenticated
using (
    profile_id = public.quata_chat_auth_profile_id()
    or exists (
        select 1
        from public.chat_sos_recipients r
        where r.sos_event_id = id
          and r.recipient_profile_id = public.quata_chat_auth_profile_id()
    )
);

drop policy if exists chat_sos_recipients_select_owner_or_recipient on public.chat_sos_recipients;
create policy chat_sos_recipients_select_owner_or_recipient
on public.chat_sos_recipients
for select
to authenticated
using (
    recipient_profile_id = public.quata_chat_auth_profile_id()
    or exists (
        select 1
        from public.chat_sos_events e
        where e.id = sos_event_id
          and e.profile_id = public.quata_chat_auth_profile_id()
    )
);

insert into storage.buckets (id, name, public)
values ('chat-attachments', 'chat-attachments', true)
on conflict (id) do update set public = excluded.public;

grant usage on schema public to anon, authenticated;
grant execute on function public.quata_chat_auth_profile_id() to anon, authenticated;
grant execute on function public.quata_chat_actor_profile_id(uuid) to anon, authenticated;
grant execute on function public.quata_chat_is_thread_participant(bigint, uuid) to anon, authenticated;
grant execute on function public.quata_chat_can_moderate(bigint, uuid) to anon, authenticated;
grant execute on function public.quata_chat_is_blocked(bigint, uuid, uuid) to anon, authenticated;
grant select on
    public.chat_threads,
    public.chat_private_threads,
    public.chat_participants,
    public.chat_messages,
    public.chat_attachments,
    public.chat_message_favorites,
    public.chat_message_reactions,
    public.chat_message_reads,
    public.chat_profile_blocks,
    public.chat_events,
    public.chat_sos_events,
    public.chat_sos_recipients
to authenticated;
