-- Native push notifications for Supabase chat.
-- Creates token storage, idempotent delivery logging, an authenticated token
-- registration RPC, and a chat_messages trigger that invokes the Edge Function.

create extension if not exists pg_net with schema extensions;

create table if not exists public.push_tokens (
    id uuid primary key default gen_random_uuid(),
    user_id uuid not null references public.community_profiles(id) on delete cascade,
    auth_user_id uuid references auth.users(id) on delete cascade,
    token text not null,
    platform text not null default 'android',
    app_version text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    last_seen_at timestamptz not null default now(),
    constraint push_tokens_token_key unique (token),
    constraint push_tokens_platform_check check (platform in ('android', 'ios', 'web'))
);

create index if not exists push_tokens_user_idx on public.push_tokens(user_id);
create index if not exists push_tokens_auth_user_idx on public.push_tokens(auth_user_id);
create index if not exists push_tokens_last_seen_idx on public.push_tokens(last_seen_at desc);

alter table public.push_tokens enable row level security;

drop policy if exists push_tokens_select_own on public.push_tokens;
create policy push_tokens_select_own
on public.push_tokens
for select
to authenticated
using (
    auth.uid() = auth_user_id
    or exists (
        select 1
        from public.community_profiles p
        where p.id = push_tokens.user_id
          and p.auth_user_id = auth.uid()
    )
);

drop policy if exists push_tokens_delete_own on public.push_tokens;
create policy push_tokens_delete_own
on public.push_tokens
for delete
to authenticated
using (
    auth.uid() = auth_user_id
    or exists (
        select 1
        from public.community_profiles p
        where p.id = push_tokens.user_id
          and p.auth_user_id = auth.uid()
    )
);

create table if not exists public.push_delivery_log (
    id bigint generated by default as identity primary key,
    message_id bigint not null references public.chat_messages(id) on delete cascade,
    profile_id uuid not null references public.community_profiles(id) on delete cascade,
    push_token_id uuid not null references public.push_tokens(id) on delete cascade,
    status text not null default 'reserved',
    error_text text,
    created_at timestamptz not null default now(),
    sent_at timestamptz,
    constraint push_delivery_log_status_check check (status in ('reserved', 'sent', 'error')),
    constraint push_delivery_log_message_profile_token_key unique (message_id, profile_id, push_token_id)
);

create index if not exists push_delivery_log_message_idx on public.push_delivery_log(message_id);
create index if not exists push_delivery_log_profile_idx on public.push_delivery_log(profile_id, created_at desc);

alter table public.push_delivery_log enable row level security;

create or replace function public.quata_register_push_token(
    p_profile_id uuid,
    p_token text,
    p_platform text default 'android'
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    v_auth_uid uuid := auth.uid();
    v_profile_auth_user_id uuid;
    v_token text := nullif(trim(coalesce(p_token, '')), '');
    v_platform text := lower(nullif(trim(coalesce(p_platform, 'android')), ''));
    v_token_id uuid;
begin
    if v_token is null then
        raise exception 'push token is required' using errcode = '22023';
    end if;

    if v_platform is null or v_platform not in ('android', 'ios', 'web') then
        v_platform := 'android';
    end if;

    select auth_user_id
    into v_profile_auth_user_id
    from public.community_profiles
    where id = p_profile_id;

    if v_profile_auth_user_id is null then
        raise exception 'profile has no auth identity' using errcode = '42501';
    end if;

    if v_auth_uid is not null and v_auth_uid <> v_profile_auth_user_id then
        raise exception 'cannot register token for another profile' using errcode = '42501';
    end if;

    insert into public.push_tokens(user_id, auth_user_id, token, platform, updated_at, last_seen_at)
    values (p_profile_id, v_profile_auth_user_id, v_token, v_platform, now(), now())
    on conflict (token) do update
    set user_id = excluded.user_id,
        auth_user_id = excluded.auth_user_id,
        platform = excluded.platform,
        updated_at = now(),
        last_seen_at = now()
    returning id into v_token_id;

    return jsonb_build_object('result', true, 'id', v_token_id);
end;
$$;

revoke all on function public.quata_register_push_token(uuid, text, text) from public;
grant execute on function public.quata_register_push_token(uuid, text, text) to authenticated;

create or replace function public.quata_enqueue_chat_push()
returns trigger
language plpgsql
security definer
set search_path = public, extensions
as $$
begin
    if new.deleted_at is not null then
        return new;
    end if;

    perform net.http_post(
        url := 'https://yrrlankpwmhluexshxnw.supabase.co/functions/v1/quata-push-dispatch',
        headers := jsonb_build_object('Content-Type', 'application/json'),
        body := jsonb_build_object('message_id', new.id),
        timeout_milliseconds := 1000
    );

    return new;
exception
    when undefined_function or insufficient_privilege or invalid_schema_name then
        return new;
end;
$$;

drop trigger if exists chat_messages_after_insert_push on public.chat_messages;
create trigger chat_messages_after_insert_push
after insert on public.chat_messages
for each row
execute function public.quata_enqueue_chat_push();
